### ISSUE TITLE
怎么把文章和比较详情页面都以.html结尾啊？

### ISSUE THREAD

**Issue by somta** [pengzhanbo/vuepress-theme-plume#110]

**Comment by pengzhanbo** [comment]
这个主题默认会自动处理页面的文件地址为 `/xx/xx/index.html` , 使得在访问的时候链接可以简写为 `/xx/xx/`，这么做的目的就是为了让页面的访问路径更 “干净”，同时也帮助处理文章 `frontmatter` 的其他字段，包括自动生成等。

主题默认做了这些事情，但是当前并没有提供配置来禁用这些行为。后续我会考虑 提供相关的配置来禁用它们，恢复为 vuepress 的默认行为。

**Comment by pengzhanbo** [comment]
新版本中提供了 [autoFrontmatter](https://theme-plume.vuejs.press/config/basic/#autofrontmatter) 选项来禁用自动生成 frontmatter， 也可以更细致化的控制禁止 自动生成 `permalink` 。
但对于已有的 md 文件中的 `frontmatter` 字段，需要手动删除它们。 
`autoFrontmatter` 禁用后，将会恢复为 VuePress 的默认行为。
