### ISSUE TITLE
DEMO带密码文章输入密码后卡死

### ISSUE THREAD

**Issue by SaturnTsen** [pengzhanbo/vuepress-theme-plume#112]
https://plume.pengzhanbo.cn/article/enx7c9s/

输入密码123456后回车，随后页面停止响应。

浏览器为 Microsoft Edge Version 126.0.2592.87 (Official build) (64-bit)

**Comment by pengzhanbo** [comment]
其实也不算是卡死，这是由于 加密算法的验证过程比较耗时，需要等待一段时间。
当前主题使用了同步验证的方式，并且没有给出过程的提示，这导致 看起来 卡住了。
我计划在下个版本中优化这里的交互逻辑，增加一些提示。

**Comment by pengzhanbo** [comment]
新版本重写了 站点加密 功能的部分逻辑以及交互。
