### ISSUE TITLE
启动打包时有sass错误警告

### ISSUE THREAD

**Issue by wuwubin** [pengzhanbo/vuepress-theme-plume#119]
![image](https://github.com/user-attachments/assets/774633cd-ea9c-4d79-8d4a-3096d42110e5)
以及底部宽度计算不准确
![image](https://github.com/user-attachments/assets/0cbc3eab-96dc-437f-b064-6dcd1867f05d)

**Comment by pengzhanbo** [comment]
关于 sass 的错误警告，请查看 https://github.com/sass/dart-sass/issues/2276 了解更多信息。

其中，如果是使用 webpack bundler 的，我会在新版本中添加配置 关闭警告信息，
而如果是使用 vite bundler 的，需要等待 vite https://github.com/vitejs/vite/issues/7116 更新。

关于 底部宽度计算 也会在下个版本中 修复。

**Comment by pengzhanbo** [comment]
#120

**Comment by pengzhanbo** [comment]
vite bundler  下的 警告信息已进行处理，不再输出提示
