### ISSUE TITLE
该框架是否有跨域解决方案

### ISSUE THREAD

**Issue by wuwubin** [pengzhanbo/vuepress-theme-plume#127]
在框架中添加自己在另外服务器搭建artalk评论服务，使用该框架存在跨域问题.
![image](https://github.com/user-attachments/assets/036304d4-af21-4eea-9a4d-710712e68be7)
当前解决方案为本地运行关闭浏览器跨域安全拦截，打包发布时使用nginx代理连接。
是否还有更优方案？

**Comment by pengzhanbo** [comment]
跨域问题应该在服务器端进行处理，在你的接口服务中配置 `Access-Control-Allow-Origin` 允许你的 站点域名请求该接口服务。或者将你的站点和服务部署在同一个域名端口下。

可以参考这篇 [文章](https://pengzhanbo.cn/article/2f45bq9x/)
