### ISSUE TITLE
代码演示 - vue 代码演示显示问题

### ISSUE THREAD

**Issue by tuyongtao-T** [pengzhanbo/vuepress-theme-plume#146]
使用文档中  代码演示模块，vue 代码演示，效果没有出来；红色区域应该是缺点东西。
![20240821183133053](https://github.com/user-attachments/assets/78f9f24a-7782-45be-9021-472cec3e5377)

**Comment by pengzhanbo** [comment]
检查发现是 vuepress-plugin-md-enhance 插件导致的问题，已提交 [issue](#4355) 和 [PR](#4356) 等待修复。

**Comment by pengzhanbo** [comment]
该问题已在 rc.103 版本中修复。
