### ISSUE TITLE
[Bug Report] CardGrid 卡片容器刷新后失效

### ISSUE THREAD

**Issue by bigtomcat6** [pengzhanbo/vuepress-theme-plume#147]
<img width="1209" alt="截屏2024-08-22 03 06 27" src="https://github.com/user-attachments/assets/3d6ec85f-99e0-4544-b720-7b8f96b12570">

点击浏览器的刷新后容器失效（如下图），如果直接通过本页链接访问这个页面这个容器也会失效的。

<img width="1207" alt="截屏2024-08-22 03 06 39" src="https://github.com/user-attachments/assets/162c9636-3435-47b5-acc0-5c77cd86d531">

**Comment by bigtomcat6** [comment]
在pnpm build后在.vuepress/dist中可复现相同问题，但是这个问题在pnpm dev时无法复现。怀疑是build的时候的bug

**Comment by pengzhanbo** [comment]
这个问题稍显得有些怪异。初步判断是在 SSR 后，在浏览器端 进行 水合 时，出现了问题。
在水合完成后，计算属性的值没有被响应式的更新到 DOM 中。
我在这一步检测到的 计算属性是发生了更新的，计算结果正确，但 DOM 没有正确显示，而实际上调整窗口大小，其响应性并没有丢失，DOM 依然有触发计算属性后的更新。

我换了另外的方式来实现组件的逻辑，在 `onMounted` 中手动进行一次计算，组件恢复了正常的表现。
