### ISSUE TITLE
[Bug Report] 代码演示模块： 浏览器的一个 API 使用报错

### ISSUE THREAD

**Issue by tuyongtao-T** [pengzhanbo/vuepress-theme-plume#149]
API： document.createDocumentFragment()
在项目中使用该API 进行元素片段创建， 在演示过程中报错。
demo如下：

::: normal-demo 

```html
<div class="box">
</div>
```

```js
const docFragment = document.createDocumentFragment();
```
:::
报错如下：
![image](https://github.com/user-attachments/assets/005ddf2f-a262-41de-9850-8bfddcc77fbc)

**Comment by pengzhanbo** [comment]
使用 `window.document.createDocumentFragment()` 而不是 `document.createDocumentFragment()`。

这是由于 code demo 是运行在 shadowDOM 内的，在 shadowDOM 内的 `document` 指向的是 `shadowDOM` 自身节点的上下文。

**Comment by tuyongtao-T** [comment]
已解决，感谢
