### ISSUE TITLE
imgLazyload 没有生效

### ISSUE THREAD

**Issue by LuckRain7** [pengzhanbo/vuepress-theme-plume#156]
按照 https://theme-plume.vuejs.press/config/plugins/markdown-enhance/ 配置了  imgLazyload，并没有生效
    
      plugins: {
            markdownEnhance: {
                imgLazyload: true
            }
        }

**Comment by pengzhanbo** [comment]
imgLazyLoad 是在 `<img>` 标签上添加 `loading="lazy"` 来实现原生支持的懒加载。

1. 请打开浏览器控制台面板，检查你的项目在运行时，`<img>` 标签 上是否有该属性。
2. 由于主题内使用了 编译缓存，在启动时跳过了未修改文件的编译，这可能导致你修改配置重启项目后，由于缓存的原因没有实时生效，可以在 `vuepress dev` 命令后添加 `--clean-cache` 清除缓存后再重启。

**Comment by LuckRain7** [comment]
> imgLazyLoad 是在 `<img>` 标签上添加 `loading="lazy"` 来实现原生支持的懒加载。
> 
> 1. 请打开浏览器控制台面板，检查你的项目在运行时，`<img>` 标签 上是否有该属性。
> 2. 由于主题内使用了 编译缓存，在启动时跳过了未修改文件的编译，这可能导致你修改配置重启项目后，由于缓存的原因没有实时生效，可以在 `vuepress dev` 命令后添加 `--clean-cache` ，在重启时清除缓存。

2. 生效 ，感谢 🙏
