### ISSUE TITLE
如何让博客列表直接作为首页?

### ISSUE THREAD

**Issue by ermaozi** [pengzhanbo/vuepress-theme-plume#161]
怎么配置才能在访问网站根目录时直接就是博客列表?

**Comment by pengzhanbo** [comment]
还没做这项配置，后面的版本有计划做这个功能。

**Comment by pengzhanbo** [comment]
@ermaozi rc.94 版本已添加 该配置支持。 https://theme-plume.vuejs.press/guide/blog/#%E8%AE%BE%E7%BD%AE%E5%8D%9A%E5%AE%A2%E4%B8%BA%E4%B8%BB%E9%A1%B5

**Comment by ermaozi** [comment]
> @ermaozi rc.94 版本已添加 该配置支持。 https://theme-plume.vuejs.press/guide/blog/#%E8%AE%BE%E7%BD%AE%E5%8D%9A%E5%AE%A2%E4%B8%BA%E4%B8%BB%E9%A1%B5

太酷了哥!
