### ISSUE TITLE
markdown渲染的一点问题

### ISSUE THREAD

**Issue by TheCoderAlex** [pengzhanbo/vuepress-theme-plume#169]
在一个已经有3个二级标题的markdown中添加一个三级标题会导致渲染出的html部分内容消失。主要集中在包含公式的段落及其以后的段落出现消失。例如以下的markdown：
```markdown
本页面将简要介绍快速排序。

## 定义

快速排序（Quicksort），又称分区交换排序（partition-exchange sort），简称”快排“，是一种被广泛运用的排序算法。

### 测试

## 基本思想

快速排序的思想是，先分两段排序，排序后再递归排序。

- 选择一个 $x$ 作为分界点： $x$ 可以是左端点的数，右端点的数、中间数或者是随机的数。排序复杂度也因分界点的选择而变化。
- 将待排序区间划分为两个子区间。其中，左子区间的所有数都满足小于等于分界点数 $x$ 。右子区间的所有数都满足大于等于分界点数 $x$ 。
- 递归的排序左边区间和右边区间。

## 参考文章
```
在添加测试这个三级标题前一切正常，添加后页面缺失元素，如下所示：
![image](https://github.com/user-attachments/assets/bcb48e63-2b8c-4c0f-80e3-ec55b30f4949)

有趣的是，我使用了本仓库中其他有多级目录的例子试了却没有任何问题。这是为什么？

**Comment by pengzhanbo** [comment]
🤔 我在我本地用你的例子重现出来了，我也有点懵。
我检查了 markdown-it  render 结果，输出正常，检查了 `vue sfc template block`，输出正常，生成的临时文件 `pages/*.vue` 输出也正常。但是在浏览器端，多出了一份 数据不对应的 同名虚拟文件，我还在排查它是从什么地方产生的。

**Comment by TheCoderAlex** [comment]
> 🤔 我在我本地用你的例子重现出来了，我也有点懵。 我检查了 markdown-it render 结果，输出正常，检查了 `vue sfc template block`，输出正常，生成的临时文件 `pages/*.vue` 输出也正常。但是在浏览器端，多出了一份 数据不对应的 同名虚拟文件，我还在排查它是从什么地方产生的。

如果把公式去掉也可以正常输出，会不会是公式的问题？

**Comment by pengzhanbo** [comment]
> 如果把公式去掉也可以正常输出，会不会是公式的问题？

我不确定根源是否在于 kateX，它可能只是 bug 的一种体现，因为从 markdown 的编译结果来看，输出是正常的，包括再进一步包装成 vue SFC 的模板字符串，它依然是正常的，不正常的地方，是经过 vite 发送到 浏览器后内容就已经被裁剪了

**Comment by pengzhanbo** [comment]
@TheCoderAlex 可以确定是在 `@vue/compiler-sfc` 这里出现了问题。

```
{
  code: 'import { createElementVNode as _createElementVNode, createTextVNode as _createTextVNode, createStaticVNode as _createStaticVNode, openBlock as _openBlock, createElementBlock as _createElementBlock } from "vue"\n' +
    '\n' +
    'export function render(_ctx, _cache) {\n' +
    '  return (_openBlock(), _createElementBlock("div", null, _cache[0] || (_cache[0] = [\n' +
    '    _createStaticVNode("<p>本页面将简要介绍快速排序。</p><h2 id=\\"定义\\" tabindex=\\"-1\\"><a class=\\"header-anchor\\" href=\\"#定义\\"><span>定义</span></a></h2><p>快速排序（Quicksort），又称分区交换排序（partition-exchange sort），简称”快排“，是一种被广泛运用的排序算法。</p><h2 id=\\"原理\\" tabindex=\\"-1\\"><a class=\\"header-anchor\\" href=\\"#原理\\"><span>原理</span></a></h2><p>111</p><h2 id=\\"xx\\" tabindex=\\"-1\\"><a class=\\"header-anchor\\" href=\\"#xx\\"><span>xx</span></a></h2><ul><li>xx</li><li>uu</li></ul><h2 id=\\"基本思想\\" tabindex=\\"-1\\"><a class=\\"header-anchor\\" href=\\"#基本思想\\"><span>基本思想</span></a></h2>", 8)\n' +
    '  ])))\n' +
    '}',
  ast: {
    type: 0,
    source: '<template><div><p>本页面将简要介绍快速排序。</p>\n' +
      '<h2 id="定义" tabindex="-1"><a class="header-anchor" href="#定义"><span>定义</span></a></h2>\n' +
      '<p>快速排序（Quicksort），又称分区交换排序（partition-exchange sort），简称”快排“，是一种被广泛运用的排序算法。</p>\n' +
      '<h2 id="原理" tabindex="-1"><a class="header-anchor" href="#原理"><span>原理</span></a></h2>\n' +
      '<p>111</p>\n' +
      '<h2 id="xx" tabindex="-1"><a class="header-anchor" href="#xx"><span>xx</span></a></h2>\n' +
      '<ul>\n' +
      '<li>xx</li>\n' +
      '<li>uu</li>\n' +
      '</ul>\n' +
      '<h2 id="基本思想" tabindex="-1"><a class="header-anchor" href="#基本思想"><span>基本思想</span></a></h2>\n' +
      '<ul>\n' +
      '<li>\n' +
      '<p>快速排序的思想是，先分两段排序，排序后再递归排序。</p>\n' +
      '</li>\n' +
      '<li>\n' +
      '<p>将待排序区间划分为两个子区间。其中，左子区间的所有数都满足小于等于分界点数 <span v-pre class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>x</mi></mrow><annotation encoding="application/x-tex">x</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.4306em;"></span><span class="mord mathnormal">x</span></span></span></span> 。右子区间的所有数都满足大于等于分界点数 <span v-pre class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>x</mi></mrow><annotation encoding="application/x-tex">x</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.4306em;"></span><span class="mord mathnormal">x</span></span></span></span> 。</p>\n' +
      '</li>\n' +
      '<li>\n' +
      '<p>递归的排序左边区间和右边区间。</p>\n' +
      '</li>\n' +
      '</ul>\n' +
      '<h2 id="参考文章" tabindex="-1"><a class="header-anchor" href="#参考文章"><span>参考文章</span></a></h2>\n' +
      '<p>呵呵</p>\n' +
      '<h2 id="源码" tabindex="-1"><a class="header-anchor" href="#源码"><span>源码</span></a></h2>\n' +
      '<p>777</p>\n' +
      '</div></template>\n' +
      '\n' +
      '\n',
  },
  source: '<div><p>本页面将简要介绍快速排序。</p>\n' +
    '<h2 id="定义" tabindex="-1"><a class="header-anchor" href="#定义"><span>定义</span></a></h2>\n' +
    '<p>快速排序（Quicksort），又称分区交换排序（partition-exchange sort），简称”快排“，是一种被广泛运用的排序算法。</p>\n' +
    '<h2 id="原理" tabindex="-1"><a class="header-anchor" href="#原理"><span>原理</span></a></h2>\n' +
    '<p>111</p>\n' +
    '<h2 id="xx" tabindex="-1"><a class="header-anchor" href="#xx"><span>xx</span></a></h2>\n' +
    '<ul>\n' +
    '<li>xx</li>\n' +
    '<li>uu</li>\n' +
    '</ul>\n' +
    '<h2 id="基本思想" tabindex="-1"><a class="header-anchor" href="#基本思想"><span>基本思想</span></a></h2>\n' +
    '<ul>\n' +
    '<li>\n' +
    '<p>快速排序的思想是，先分两段排序，排序后再递归排序。</p>\n' +
    '</li>\n' +
    '<li>\n' +
    '<p>将待排序区间划分为两个子区间。其中，左子区间的所有数都满足小于等于分界点数 <span v-pre class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>x</mi></mrow><annotation encoding="application/x-tex">x</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.4306em;"></span><span class="mord mathnormal">x</span></span></span></span> 。右子区间的所有数都满足大于等于分界点数 <span v-pre class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>x</mi></mrow><annotation encoding="application/x-tex">x</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.4306em;"></span><span class="mord mathnormal">x</span></span></span></span> 。</p>\n' +
    '</li>\n' +
    '<li>\n' +
    '<p>递归的排序左边区间和右边区间。</p>\n' +
    '</li>\n' +
    '</ul>\n' +
    '<h2 id="参考文章" tabindex="-1"><a class="header-anchor" href="#参考文章"><span>参考文章</span></a></h2>\n' +
    '<p>呵呵</p>\n' +
    '<h2 id="源码" tabindex="-1"><a class="header-anchor" href="#源码"><span>源码</span></a></h2>\n' +
    '<p>777</p>\n' +
    '</div>',
}
```

可以看到， 最终产物 `code` 和 `source` 明显被裁剪了一部分。具体原因是什么，这个需要深入分析了。
这应该是 `vue` 的 bug 了。

**Comment by TheCoderAlex** [comment]
@pengzhanbo 在markdown文件中启用 `<!-- markdownlint-disable md025 --> `注释后在本地dev环境中可以正常完整显示了，但是 `vuepress build docs` 生成的静态页面仍然无法显示

**Comment by pengzhanbo** [comment]
@TheCoderAlex 

[vue playground](https://play.vuejs.org/#eNrtV19v01YU/yqW90piIGgamRdpm3jYNPb/MS8X+xKb+p9sp8mEKpl07RI1aapoLaikKlRd2Vb6RwqFxG3pdwFfO3nqV+BcO3EdiEDqE0hV1Zt7f/ec43PO7xzn5C77tWGkp4uYzbK8jVVDQTbO5TWG4UV5OscbOb/9dPD4YLC2Qfbng12nv3XPO1wIDhvkZHvgrPuLLeI2XzsVnjNAjZeuMrL4VZ4lu6ter5ZnGRvdkjURlwFLXcmzOR4xgoIsC84SRiI2U0gTJN0EUcnEtwH+bKSb4y0DabnoyHPhgecQ/EtX6bOMXNKH06PqL0VZmLJ00z49qp0e1UmzGjzZJ9V5Unc9d9NvbMSSBjJt2ZZ1LYXLgoS0AmbO9CBK0HvlrIF50HjltAH0H+x5XcAb/Y1t0jvxOw/7J0vB3/8Gq39GVoPd+35nOZGJTJQJ/2Chv7d8vkyMdIeZiI7jmciMZX3dBbp8Z82f7Zwz92MWRgwkwA/yQBMSSkLGKAlzVWDA6276uwej9NejDVlaJPONgdMix62366io0FWRcwOn5i/8B6n3uv8zoTvMdMowcRzJFBRseeTqOJpSkS2pCr2kO6asKloYvG0bWY4rlUrpUiatmwXuyvXrX3A3QSZcbv4Q2sMq0mxZsEDb1Euwyrkyz8EKSwggTdNtRMuIwZqgi7JWAOvIMBRZCGGunIqcA70zYdBP2OaoaxQK0zohCMmmITDIlFFKkkURa3Blm0X8TtC3kPUuaIGoDfqW/YeCQ+blgmRnL6evZS5/jtUvqcKkh6u6KTLUN003VUSTCEEMuZ/wwXjHba/rAtfBcj2o9E6PVi/o+ojpIs097/Af6FHyYivY3gPGaOMu74fvzU4See3c87o7g/vPYO9XV/rOHGgNVpt+2x0JVIYNvdnw1yrE3fJ66+Tho7gWQCxq474Dxh+Q+krY6NDdUY/DNwt5OTe0UXfhUaTaCt8aLrw4oPHJzlKEgx6Zew7uUDdfbMU4daTm+O0auDOYPfYPH/efd8h+03MXg50arLEvIHBRlx9xXVKGm50PELv55ILYT5DYRMtH3/rx8AS93H/ZG/Z+i76B4mNCj4umgnjaaVb6zqy/8lew/eic086YhdG0kwAnTDscnYvpZ2Japn/sJda2BF27LRfSdyxdg4H6Lp2j86ygq4asYPMng7Jr5dksE97QO6Qoeun7EKOUXRrhgoSFqQn4HQvKJQubn01sYXMa+IzvbGQWMFBJr2/89iMuwz6+VHWxqID0ey5/xZauFKmPkdg3RU0EtxNyobffqQaMylDLv1s3yjbWrFFQYc2B5Ewon2fhV8W37wn9zN1M+lqol9dm2Jk3jDBPTg==)

这是一个可以稳定复现的 bug，我还是去 vue 社区反馈下吧

**Comment by TheCoderAlex** [comment]
> @TheCoderAlex 
> 
> 
> 
> [vue playground](https://play.vuejs.org/#eNrtV19v01YU/yqW90piIGgamRdpm3jYNPb/MS8X+xKb+p9sp8mEKpl07RI1aapoLaikKlRd2Vb6RwqFxG3pdwFfO3nqV+BcO3EdiEDqE0hV1Zt7f/ec43PO7xzn5C77tWGkp4uYzbK8jVVDQTbO5TWG4UV5OscbOb/9dPD4YLC2Qfbng12nv3XPO1wIDhvkZHvgrPuLLeI2XzsVnjNAjZeuMrL4VZ4lu6ter5ZnGRvdkjURlwFLXcmzOR4xgoIsC84SRiI2U0gTJN0EUcnEtwH+bKSb4y0DabnoyHPhgecQ/EtX6bOMXNKH06PqL0VZmLJ00z49qp0e1UmzGjzZJ9V5Unc9d9NvbMSSBjJt2ZZ1LYXLgoS0AmbO9CBK0HvlrIF50HjltAH0H+x5XcAb/Y1t0jvxOw/7J0vB3/8Gq39GVoPd+35nOZGJTJQJ/2Chv7d8vkyMdIeZiI7jmciMZX3dBbp8Z82f7Zwz92MWRgwkwA/yQBMSSkLGKAlzVWDA6276uwej9NejDVlaJPONgdMix62366io0FWRcwOn5i/8B6n3uv8zoTvMdMowcRzJFBRseeTqOJpSkS2pCr2kO6asKloYvG0bWY4rlUrpUiatmwXuyvXrX3A3QSZcbv4Q2sMq0mxZsEDb1Euwyrkyz8EKSwggTdNtRMuIwZqgi7JWAOvIMBRZCGGunIqcA70zYdBP2OaoaxQK0zohCMmmITDIlFFKkkURa3Blm0X8TtC3kPUuaIGoDfqW/YeCQ+blgmRnL6evZS5/jtUvqcKkh6u6KTLUN003VUSTCEEMuZ/wwXjHba/rAtfBcj2o9E6PVi/o+ojpIs097/Af6FHyYivY3gPGaOMu74fvzU4See3c87o7g/vPYO9XV/rOHGgNVpt+2x0JVIYNvdnw1yrE3fJ66+Tho7gWQCxq474Dxh+Q+krY6NDdUY/DNwt5OTe0UXfhUaTaCt8aLrw4oPHJzlKEgx6Zew7uUDdfbMU4daTm+O0auDOYPfYPH/efd8h+03MXg50arLEvIHBRlx9xXVKGm50PELv55ILYT5DYRMtH3/rx8AS93H/ZG/Z+i76B4mNCj4umgnjaaVb6zqy/8lew/eic086YhdG0kwAnTDscnYvpZ2Japn/sJda2BF27LRfSdyxdg4H6Lp2j86ygq4asYPMng7Jr5dksE97QO6Qoeun7EKOUXRrhgoSFqQn4HQvKJQubn01sYXMa+IzvbGQWMFBJr2/89iMuwz6+VHWxqID0ey5/xZauFKmPkdg3RU0EtxNyobffqQaMylDLv1s3yjbWrFFQYc2B5Ewon2fhV8W37wn9zN1M+lqol9dm2Jk3jDBPTg==)
> 
> 
> 
> 这是一个可以稳定复现的 bug，我还是去 vue 社区反馈下吧

好的，多谢！

**Comment by pengzhanbo** [comment]
@TheCoderAlex [#11879](https://github.com/vuejs/core/issues/11879)

**Comment by TheCoderAlex** [comment]
> @TheCoderAlex [#11879](https://github.com/vuejs/core/issues/11879)

好的。我将vue版本锁到3.4了，现在没啥问题，等更新。

**Comment by coderwei99** [comment]
一种工作方式: 移除外层的div [vue playground](https://play.vuejs.org/#eNrtV1tv2lYc/yqW91pwW7ppZR7SNvVh07r7I9J0ak6xG99km8BURXLJkoECIUJLWqVEaaMs3ZblIrG0QJLmu7Q+NjzlK+x/bGwg0G5Ce5kWJMw5/9v5/a8c32c/0vX4bA6zSZa3sKLLyMKptMrAh9dTbuOP3tOj3sYWOVz09u3uzgPneMk7rpKz3Z696S7XSaf22i7ynB7qiNcZKfNhmiX76067nGYZC92R1AwuAC12Lc2meMQIMjJN2IsYZbARQ6ogagaIiga+C+R3Qt0Ub+pITQVbnvM3PIfgK14fYBzGcn5S+jonCTOmZljnJ+Xzkwqplbxnh6S0SCodp7PtVrciSR0ZlmRJmhrDBUFEahYzAz3wFvRe2RtgHjRe2Q0guo8OnBbQq92tXdI+c5uPu2cr3s+/eus/Bla9/Yduc/VCRBJBRNyjpe7B6nQRCXX7EQm2oxFJjGVgswPpc+0Nd745ZR5GLITZGCL+o5zQ4PjSED2akIUSZMNpbbv7R2EqKsGCrCyTxWrPrpPT+oXa6lvOyf0zYC1LqZ5ddpd+g5Q4rd8ZHx4zG9MNHHk2A9VcCKGPUmMKskRFBmZosW+379MEDdGi8gwyJBQTpUwGq8CyjBweO+EOMseJJohaaXb0OPoxrR9k7OdByopW8mr8RuLqe1j5gFqYhEbRjAxD4auaoSDqQiHKxIQfxjltOK0ORN1brXjF9vnJehCsYSRTxI2nK6agyKpfRJalJzkun8/H84m4ZmS5azdvvs/dBhn/cfvzsVBDsE2sINWSBHOMBUzF0PIT6JQjUZfhOUGLe4Maj1RVsxBteAargpaR1CzgRrouS4JP5gqxwG2wPRAeB829CTWcDZ5OTtp/uoQGB5LagXP8C7QyebHj7R5AOdH+Xj30R21zmPLafuC09noP/4S1W1rr2gug1VuvuY1OKFDs9/121d0oks6O094kj59EhQpiQYd3bTD+iFTW/HkAjT88BOCvibxc6FuqdOBAUqr7I6YDUwYmA9lbCeigTRaeAygK9sVORKdwyrbbKAOo3vype/y0+7xJDmtOZ9nbK8MzQgQC088Zv18upu6yff5X7UNLsNb8m8rbfnZZeZeV9+/890+amMENK7q0wijsvmz3R2edjvFoO6rNc9H9a3DLrBW79ry79pO3+2TKW+aIhfCWOUQcv2Xy3NCrCnuFtUxBU+9K2fg9U1PhTeY+BZlmBU3RJRkbX+q0HMw0m2R8DuUhWdbyn/k0msUrIV0QsTAzgX7PhPpKwuIrA5vYmIUURzwLGVkM2aXsW99+gQuwjpiKlsnJIP0W5jfY1OQcxRiIfZxTMwB7SM5H+6miw+sJFP935q2ChVUzdMovQ5Cc8+XTLLzOffIW1wdwE/GEr5dW5yCK389ig9qEACbi78ZvsHN/AQXxbAA=)

**Comment by TheCoderAlex** [comment]
> @TheCoderAlex 该bug 已在 [vue@3.5.5](https://github.com/vuejs/core/commit/1d99d61c1bd77f9ea6743f6214a82add8346a121) 中修复。

收到，已更新。关闭issue了。
