### ISSUE TITLE
pnpm run docs:dev出错

### ISSUE THREAD

**Issue by ztygod** [pengzhanbo/vuepress-theme-plume#170]
模块丢失问题

![屏幕截图 2024-09-12 155923](https://github.com/user-attachments/assets/4f9bf68c-8c80-4225-b979-859dca5bea05)

**Comment by pengzhanbo** [comment]
尝试将  node_modules 目录直接删除，以及 `package.lock.json` 或 `pnpm-lock.yaml` 文件删除，然后重新执行 `npm i` 或 `pnpm i` 重新安装依赖。

**Comment by ztygod** [comment]
谢谢已经解决。
