### ISSUE TITLE
请教GitHub Pages部署具体操作

### ISSUE THREAD

**Issue by ztygod** [pengzhanbo/vuepress-theme-plume#173]
关于GitHub Pages的部署有什么教程吗，vuepress官网没有给出具体操作，网上教程内容版本不一样，难以判断是否有用，本人主要是卡在GitHub Actions。

**Comment by ztygod** [comment]
本人对这方面不是很熟悉，抱歉打扰了

**Comment by pengzhanbo** [comment]
1. 主题提供了 部署的 github pages 的 [说明文档](https://theme-plume.vuejs.press/guide/deployment/#github-pages) 按照这个添加配置。
2. 你需要在你的仓库配置的中 `setting > Code and automation > Actions > General` 中，将页面拉到底部看到  `Workflow permissions`，启用 `Read and write permissions` 这个选项。
  ![QQ_1726224304559](https://github.com/user-attachments/assets/1a4a9c6b-2b1c-45fb-bf8e-248546cde6fc)
3. 在 `setting > Code and automation > Pages` 中，配置 `branch` 为 `gh-pages`。

**Comment by ztygod** [comment]
pnpm版本不同导致first commit构建失败
![屏幕截图 2024-09-13 215021](https://github.com/user-attachments/assets/461a4cca-a9a9-4546-897e-aa1e22aa6ac8)

我手动改了deploy.yml中的pnpm版本号为9.5.0
![屏幕截图 2024-09-13 215231](https://github.com/user-attachments/assets/f58e3ca5-a015-46c1-9bfe-2e3cb88a3e36)

再次运行结果还是一样，请问有什么解决办法吗

**Comment by ztygod** [comment]
现在又可以展现页面了，但是first commit重新运行任然错误，不过好像不影响运行😂😂😂

**Comment by pengzhanbo** [comment]
pnpm 版本，你先看看你的 仓库中的 `package.json` 中 `packageManager` 字段中的版本，将其改为 `pnpm@9.10.0` 这是是 pnpm 的最新版本。 
改完后如果你本地运行 pnpm 提示版本不对，将你本地的 pnpm 也升级到最新即可。

**Comment by pengzhanbo** [comment]
或者直接删除红框部分声明的 pnpm 版本：
![QQ_1726380840606](https://github.com/user-attachments/assets/08dc5aa4-a675-481d-893b-4fd4f16641ce)
此时会使用 package.json 中 packageManager 声明的 pnpm 版本。

**Comment by ztygod** [comment]
谢谢已经解决，网站已部署成功
