### ISSUE TITLE
文档侧边栏优化建议

### ISSUE THREAD

**Issue by wu-clan** [pengzhanbo/vuepress-theme-plume#176]
建议根据 ecosystem 侧边栏文档更新示例：https://ecosystem.vuejs.press/zh/themes/default/config.html#sidebar

着重体现 prefix 配置的坑，应为此参数如果不以 `/` 结尾将失效

**Comment by pengzhanbo** [comment]
我想想这块的文档该怎么补充调整，因为我做这块的目的本就是为了简化配置和使用门槛，但现在看来好像在文档这一方面没有达到预期效果。

**Comment by pengzhanbo** [comment]
文档已更新补充，<https://theme-plume.vuejs.press/guide/document/#%E5%85%B3%E4%BA%8E-prefix>

**Comment by wu-clan** [comment]
Hi, @pengzhanbo 

我仍然认为这不是很好的示例，我尝试通过 PR 提供建议，但是我在本地启动不了预览

![image](https://github.com/user-attachments/assets/05eccbab-a272-433a-a4b9-2c9408214477)


> 建议根据 ecosystem 侧边栏文档更新示例：https://ecosystem.vuejs.press/zh/themes/default/config.html#sidebar
> 
> 着重体现 prefix 配置的坑，应为此参数如果不以 `/` 结尾将失效

这里有很好的示例，建议采取类似的代码声明，例如：
- 示例1：
  ```js
  export default defineUserConfig({
    theme: plumeTheme({
      // 当传入类型为 `string` 时
      sidebar: [
          '/guide/intro.md',
          '/guide/getting-start.md',
          '/config/config-file.md',
          // ...
      ]
    })
  })
  ```
- 示例2
  ```js
  export default defineUserConfig({
    theme: plumeTheme({
      // 当传入类型为 `SidebarItem` 时
      sidebar: 
        { text: '介绍', link: '/guide/intro' },
        { text: '快速上手', link: '/guide/getting-start' },
        // ...
    })
  })
  ```
- ...

我知道上面的示例可能是错误的，因为有这个说明，但是删除此声明，并采用代码创建 notes 相关结构可能更加清晰
![image](https://github.com/user-attachments/assets/6d56e191-9af9-4de2-a864-39bea69e3f6e)

另外值得注意的是，确保文档内 prefix 拼接后的路径正确，原因请查看文档此处：https://theme-plume.vuejs.press/config/sidebar/#%E9%80%9A%E7%94%A8-sidebar-%E9%85%8D%E7%BD%AE

如果使用这种侧边栏方式定义 prefix，则 prefix 必须以 `/` 结果，否则将不起作用，我不确定 notes 中使用 prefix 是否存在相同问题，因为我在本地安装时总是遇到错误（未知原因），这导致无法测试（因为我不想再手动安装）

![image](https://github.com/user-attachments/assets/450b0c19-b499-4e73-a515-fac3d979a3a6)

**Comment by pengzhanbo** [comment]
> 我尝试通过 PR 提供建议，但是我在本地启动不了预览

在本地首先需要执行 `pnpm i && pnpm build`，安装依赖和构建主题、插件等的生产包，然后再运行 `pnpm docs:dev` 启动 文档的开发服务。

> 我知道上面的示例可能是错误的，因为有这个说明，但是删除此声明，并采用代码创建 notes 相关结构可能更加清晰

我这里开始也是从 `defineUserConfig` 开始写，但是这样做的 notes -> sidebar 的嵌套层级有点深了，才选择了提取到外部。 这里我应该换成用 `defineNotesConfig` 和 `defineNoteConfig` 作为先导说明 会比较好。

> 如果使用这种侧边栏方式定义 prefix，则 prefix 必须以 / 结果，否则将不起作用，

这里我需要重新审查下源码，因为 notes 里的 sidebar 最终也是完成解析后跟 sidebar 合并为一个对象保存为数据文件的。

> 因为我在本地安装时总是遇到错误（未知原因），这导致无法测试（因为我不想再手动安装）

我在本地验证，发现是在执行 安装依赖这一步出现问题，可以先在这一步选择 No 跳过自动安装依赖。后续我再修复。
