### ISSUE TITLE
请教代码块宽度配置

### ISSUE THREAD

**Issue by JianpengChang** [pengzhanbo/vuepress-theme-plume#178]
代码块，或者整个页面的宽度能够配置吗？如果一行的代码较长，左右拖动看着不太方便。而且对于宽屏的屏幕，文章也才只占用了中间一部分。vuepress的repo里有对default theme的解决方法，但是用在plume，并没有成功。

**Comment by pengzhanbo** [comment]
这个主题不是在 
vuepress 的  default theme 的基础上开发的，而是重写了所有的内容，因此 default theme 的解决方法并不适用于这个主题。

这个主题默认的屏幕最大适配宽度是 1440px，个人认为在这个尺寸下的阅读体验是相对比较舒服的，如果内容宽度再宽，比如在 1980 宽度下 眼睛会看的很累。

关于 最大适配宽度，目前主题还没有提供比较简单的方案去修改，因为这部分主题也是通过 媒体查询 来控制页面宽度的，尽可能的适配了 手机、平板、最大到 1440px 的尺寸。

对于 单行代码较长 的情况，我认为可以通过 根据 代码的 词法语法、表达式等，遵循某些代码的标准规范进行书写，一般不会出现很长的情况。
