### ISSUE TITLE
自定义首页section之间的滑动

### ISSUE THREAD

**Issue by HaoboGu** [pengzhanbo/vuepress-theme-plume#189]
首先感谢开源了如此cooool的主题！ 我有一个问题，不知道现在是否能实现：

1. 在首页中，点击这里的按键：
<img width="1500" alt="image" src="https://github.com/user-attachments/assets/91fd3c6c-5dc7-4973-a14b-2ced241b8788">

2. 首页自动下滑，滑动到下一个section：
<img width="1279" alt="image" src="https://github.com/user-attachments/assets/c950e2d3-6b38-4127-bf58-89f7bbccd9b4">

我在文档里面似乎没有找到相关的配置，如果可以实现的话，应该如何配置呢？

**Comment by pengzhanbo** [comment]
最简单的方法就是 给下方的 features 加一个 id，然后 button 的 link 配置为 #{id}  ：
```md
---
config:
  - type: hero
    action:
      - theme: brand
        text: 快速开始 →
        link: '#feat-1'
  - type: features
    id: feat-1
---
```

但目前这样的配置在 交互上存在一些体验上的问题，滚动结束后，section 没有与 导航栏对齐，或者没有与 窗口对齐。
体验上的问题会在下个版本中改进，但你现在就可以这样配置了。

**Comment by HaoboGu** [comment]
非常感谢 💓
