### ISSUE TITLE
移动端博客首页显示问题

### ISSUE THREAD

**Issue by SingleMoonlight** [pengzhanbo/vuepress-theme-plume#210]
### 问题描述
主题提供了将[博客设为主页](https://theme-plume.vuejs.press/guide/blog/#%E8%AE%BE%E7%BD%AE%E5%8D%9A%E5%AE%A2%E4%B8%BA%E4%B8%BB%E9%A1%B5)的方式，使用过程中发现，当将博客设为主页时：
```
---
pageLayout: home
config:
  - type: blog
---
```
移动端，或者在 PC 端将浏览器窗口宽度缩小至 418px，触发自适应，此时各个博客的卡片背景色完全一致，不再显示卡片样式，观感上不易区分。

### 对比测试
如果不将博客配置为首页，而是默认配置，单独使用首页，则没有这个问题。可以直接在官网的两个博客[案例](https://theme-plume.vuejs.press/demos/)中直接对比复现。

另外有个问题想请问一下哈，现在主题在不断开发完善、迭代，初次使用基于某一个版本，后续要如何更新呢，我试过重新运行`npm init vuepress-theme-plume@latest`，但是需要再走一遍向导流程，我不确定是否可行。如果在[安装使用](https://theme-plume.vuejs.press/guide/quick-start/)里加一个说明就更好了。

**Comment by pengzhanbo** [comment]
更新主题仅需要把 主题的 版本号改为最新，然后运行 `npm i` 或者 `pnpm i` 重新安装依赖即可。
一般在安装完成后 主题也会告诉你 是否有必要对 `vuepress` 也进行版本升级。

**Comment by pengzhanbo** [comment]
或者 vuepress 有一个自带的内置 cli 工具，直接运行 `npx vp-update` 也可以进行版本更新检查

**Comment by SingleMoonlight** [comment]
好的，感谢！
