### ISSUE TITLE
构建项目运行后，控制台报错

### ISSUE THREAD

**Issue by dubaomin1999** [pengzhanbo/vuepress-theme-plume#211]
![Snipaste_2024-09-24_16-09-40](https://github.com/user-attachments/assets/8aa36703-b20a-412b-9a49-9e0997cac5ec)
![Snipaste_2024-09-24_16-08-50](https://github.com/user-attachments/assets/ea2c7d3e-30ab-420b-b0f3-7883ffdc7d64)

**Comment by dubaomin1999** [comment]
node版本20.12.2

**Comment by pengzhanbo** [comment]
已排查到问题，下个版本修复
