### ISSUE TITLE
希望可以在通用组件<VPLink />中的点击事件加入阻止冒泡

### ISSUE THREAD

**Issue by dubaomin1999** [pengzhanbo/vuepress-theme-plume#233]
### 检查清单

- [X] 我搜索了现有问题，没有其他人请求类似功能。
- [X] 我认为25%以上的用户对此功能持积极态度。

### 描述该功能

![image](https://github.com/user-attachments/assets/1c2f043b-5402-45ec-a038-6c0a450638f8)

**Comment by pengzhanbo** [comment]
为什么需要 阻止冒泡？

**Comment by dubaomin1999** [comment]
> 为什么需要 阻止冒泡？

某些场景需要组件嵌套，我希望在触发内层某元素的事件的时候。不想触发外层跳转

**Comment by pengzhanbo** [comment]
> 某些场景需要组件嵌套，我希望在触发内层某元素的事件的时候。不想触发外层跳转

那应该是在 内层元素上 阻止事件冒泡，而不是在外层元素。

**Comment by dubaomin1999** [comment]
> > 某些场景需要组件嵌套，我希望在触发内层某元素的事件的时候。不想触发外层跳转
> 
> 那应该是在 内层元素上 阻止事件冒泡，而不是在外层元素。

我内层元素就有VPLink

**Comment by pengzhanbo** [comment]
对于 自定义链接，并不一定需要使用 `<VPLink />` 组件，你可以直接使用 `<a> 标签写，然后通过 `vuepress/client` 导出的 `useRouter` 拿到路由实例，也可以用 `vuepress-theme-plume/composables` 导出的 `useLink` 处理 `link` 等。

`<VPLink />` 组件实质上是为了使 主题内部的 链接元素行为能够符合 `<a />` 的行为，为了在 路由跳转时保证页面的过渡动画而进行的一层包装，它的行为实质上与 `<a />` 无异。

**Comment by dubaomin1999** [comment]
> 对于 自定义链接，并不一定需要使用 `<VPLink />` 组件，你可以直接使用 `<a>` 标签写，然后通过 `vuepress/client` 导出的 `useRouter` 拿到路由实例，也可以用 `vuepress-theme-plume/composables` 导出的 `useLink` 处理 `link` 等。
> 
> `<VPLink />` 组件实质上是为了使 主题内部的 链接元素行为能够符合 `<a />` 的行为，为了在 路由跳转时保证页面的过渡动画而进行的一层包装，它的行为实质上与 `<a />` 无异。

好的
