### ISSUE TITLE
[Bug] 自定义区域类型错误

### ISSUE THREAD

**Issue by somta** [pengzhanbo/vuepress-theme-plume#259]
### 检查清单

- [X] 我正在使用**LTS**版本的Node.js。
- [X] 我正在使用 **最新 v2 版本** 的 VuePress 和 VuePress 官方插件。
- [X] 我正在使用此仓库中的 **最新版本** 的 vuepress-theme-plume 及其所有插件。
- [X] 我按照文档操作，并仔细检查了我的配置。

### 包名

vuepress-theme-plume

### 你正在使用哪个操作系统？

- [ ] macOS
- [X] Windows
- [ ] Linux

### 描述该错误

参考这里写一个自定义的区域类型，出现如下错误 https://theme-plume.vuejs.press/guide/custom-home/#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%8C%BA%E5%9F%9F%E7%B1%BB%E5%9E%8B

![image](https://github.com/user-attachments/assets/32fb92bb-1d96-45a1-898f-e388ca3e0edb)

**Comment by pengzhanbo** [comment]
如果是声明式的导入的话，组件名应该是 `VPHomeBox`。

主题默认注册了 `<HomeBox />` 和 `<VPHomeBox />` 两个全局组件，你可以直接使用它们。 

这里我在文档中写错了，稍后我修改下文档。

**Comment by somta** [comment]
![image](https://github.com/user-attachments/assets/a93c3191-551d-403e-b0e0-6d702598d0e4)
还是会出现这个错误，有没有微信交流群啊？

**Comment by pengzhanbo** [comment]
先使用以下方式导入类型：
```ts
import type {PlumeHomeConfigBase} from 'vuepress-theme-plume'
import { VPHomeBox } from 'vuepress-theme-plume/client'
```
很奇怪，我在 `vuepress-theme-plume/client` 也导出了相同的类型，但却提示解析导入错误。后面我再看下问题原因。
