### ISSUE TITLE
[Feature Request] 文章加密的功能是在那块实现的，我想基于这个实现一个付费阅读文章的功能

### ISSUE THREAD

**Issue by somta** [pengzhanbo/vuepress-theme-plume#260]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

文章加密的功能是在那块实现的，我想基于这个实现一个付费阅读文章的功能

**Comment by pengzhanbo** [comment]
vuepress 是一个纯静态的 站点生成器，文章内容会被直接编译到 js 和 html 文件中， 主题的 加密功能只是将 内容编译到 html文件中给禁用了，但是依然会保留在 js 文件中，用户依然可以直接从 js 中获取到完整的 文章内容。 我也在 加密功能的文章中说明了不要将 加密功能认为是 安全可靠的，它只是看起来加密了内容，但是并不妨碍懂 vuepress 的人直接获得文章内容。 

你应该跟 其它的 CMS 结合起来使用，做严格的后台校验再返回内容，才能做到 安全可靠的 付费阅读。

**Comment by somta** [comment]
我并不打算做严格可靠的付费阅读，大部分人不会破解就好了

**Comment by pengzhanbo** [comment]
加密功能相关的源代码在 [components](https://github.com/pengzhanbo/vuepress-theme-plume/tree/main/theme/src/client/components) 的 `VPEncryptForm.vue` / `VPEncryptGlobal.vue` / `VPEncryptPage.vue` ，可以使用 [组件覆写](https://theme-plume.vuejs.press/guide/component-overrides/) 重写它们。

**Comment by somta** [comment]
好的  感谢
