### ISSUE TITLE
如何使用 Algolia DocSearch 索引本主题

### ISSUE THREAD

**Issue by huankong233** [pengzhanbo/vuepress-theme-plume#27]
请教一下如何使用 Algolia DocSearch 索引本主题

以下为我的配置文件，records 一直都是空的 🤔
~~~ js
new Crawler({
  rateLimit: 8,
  maxDepth: 10,
  startUrls: ["https://blog.huankong.top/"],
  renderJavaScript: false,
  sitemaps: ["https://blog.huankong.top/sitemap.xml"],
  ignoreCanonicalTo: false,
  discoveryPatterns: ["https://blog.huankong.top/**"],
  schedule: "at 02:00 every 1 day",
  actions: [
    {
      indexName: "huankong",
      pathsToMatch: ["https://blog.huankong.top/**"],
      recordExtractor: ({ $, helpers }) => {
        return helpers.docsearch({
          recordProps: {
            lvl0: {
              selectors: ".sidebar-item.is-active",
              defaultValue: "Documentation",
            },
            lvl1: ".content-container h1",
            lvl2: ".content-container h2",
            lvl3: ".content-container h3",
            lvl4: ".content-container h4",
            lvl5: ".content-container h5",
            lvl6: ".content-container h5",
            content: ".content-container p, .content-container li",
          },
          indexHeadings: true,
        });
      },
    },
  ],
  initialIndexSettings: {
    huankong: {
      attributesForFaceting: ["type", "lang", "language", "version"],
      attributesToRetrieve: [
        "hierarchy",
        "content",
        "anchor",
        "url",
        "url_without_anchor",
        "type",
      ],
      attributesToHighlight: ["hierarchy", "hierarchy_camel", "content"],
      attributesToSnippet: ["content:10"],
      camelCaseAttributes: ["hierarchy", "hierarchy_radio", "content"],
      searchableAttributes: [
        "unordered(hierarchy_radio_camel.lvl0)",
        "unordered(hierarchy_radio.lvl0)",
        "unordered(hierarchy_radio_camel.lvl1)",
        "unordered(hierarchy_radio.lvl1)",
        "unordered(hierarchy_radio_camel.lvl2)",
        "unordered(hierarchy_radio.lvl2)",
        "unordered(hierarchy_radio_camel.lvl3)",
        "unordered(hierarchy_radio.lvl3)",
        "unordered(hierarchy_radio_camel.lvl4)",
        "unordered(hierarchy_radio.lvl4)",
        "unordered(hierarchy_radio_camel.lvl5)",
        "unordered(hierarchy_radio.lvl5)",
        "unordered(hierarchy_radio_camel.lvl6)",
        "unordered(hierarchy_radio.lvl6)",
        "unordered(hierarchy_camel.lvl0)",
        "unordered(hierarchy.lvl0)",
        "unordered(hierarchy_camel.lvl1)",
        "unordered(hierarchy.lvl1)",
        "unordered(hierarchy_camel.lvl2)",
        "unordered(hierarchy.lvl2)",
        "unordered(hierarchy_camel.lvl3)",
        "unordered(hierarchy.lvl3)",
        "unordered(hierarchy_camel.lvl4)",
        "unordered(hierarchy.lvl4)",
        "unordered(hierarchy_camel.lvl5)",
        "unordered(hierarchy.lvl5)",
        "unordered(hierarchy_camel.lvl6)",
        "unordered(hierarchy.lvl6)",
        "content",
      ],
      distinct: true,
      attributeForDistinct: "url",
      customRanking: [
        "desc(weight.pageRank)",
        "desc(weight.level)",
        "asc(weight.position)",
      ],
      ranking: [
        "words",
        "filters",
        "typo",
        "attribute",
        "proximity",
        "exact",
        "custom",
      ],
      highlightPreTag: '<span class="algolia-docsearch-suggestion--highlight">',
      highlightPostTag: "</span>",
      minWordSizefor1Typo: 3,
      minWordSizefor2Typos: 7,
      allowTyposOnNumericTokens: false,
      minProximity: 1,
      ignorePlurals: true,
      advancedSyntax: true,
      attributeCriteriaComputedByMinProximity: true,
      removeWordsIfNoResults: "allOptional",
    },
  },
  appId: "U198Y5GBFG",
  apiKey: "xxxxx",
});
~~~

**Comment by huankong233** [comment]
现在最新的那个编译好像还会报错 🤔

~~~ text
[Vue warn]: Invalid watch source:  { open: false } A watch source can only be a getter/effect function, a ref, a reactive object, or an array of these types.
~~~

**Comment by pengzhanbo** [comment]
```js
        recordProps: {
            lvl0: {
              selectors: ".sidebar-item.is-active",
              defaultValue: "Documentation",
            },
            lvl1: ".content-container h1",
            lvl2: ".content-container h2",
            lvl3: ".content-container h3",
            lvl4: ".content-container h4",
            lvl5: ".content-container h5",
            lvl6: ".content-container h5",
            content: ".content-container p, .content-container li",
          },
```

这部分的内容中， 替换内容为
```js
      recordProps: {
            lvl1: ".plume-theme-content h1",
            content: ".plume-theme-content p, .plume-theme-content li",
            lvl0: {
              selectors: "p.sidebar-heading.active",
              defaultValue: "Documentation",
            },
            lvl2: ".plume-theme-content h2",
            lvl3: ".plume-theme-content h3",
            lvl4: ".plume-theme-content h4",
            lvl5: ".plume-theme-content h5",
            lang: "",
            tags: {
              defaultValue: ["v2"],
            },
          },
```

Algolia DocSearch 是通过在线爬虫抓取网站内容，然后再生成 搜索索引数据库的，首先需要确保 站点已部署并且可访问。
默认情况下它会定时自动爬取数据，也可以在 `Overview` 选项卡页面的右上角，点击 `restart clawling` 手动触发爬取。

**Comment by huankong233** [comment]
> ```js
>         recordProps: {
>             lvl0: {
>               selectors: ".sidebar-item.is-active",
>               defaultValue: "Documentation",
>             },
>             lvl1: ".content-container h1",
>             lvl2: ".content-container h2",
>             lvl3: ".content-container h3",
>             lvl4: ".content-container h4",
>             lvl5: ".content-container h5",
>             lvl6: ".content-container h5",
>             content: ".content-container p, .content-container li",
>           },
> ```
> 
> 这部分的内容中， 替换内容为
> 
> ```js
>       recordProps: {
>             lvl1: ".plume-theme-content h1",
>             content: ".plume-theme-content p, .plume-theme-content li",
>             lvl0: {
>               selectors: "p.sidebar-heading.active",
>               defaultValue: "Documentation",
>             },
>             lvl2: ".plume-theme-content h2",
>             lvl3: ".plume-theme-content h3",
>             lvl4: ".plume-theme-content h4",
>             lvl5: ".plume-theme-content h5",
>             lang: "",
>             tags: {
>               defaultValue: ["v2"],
>             },
>           },
> ```
> 
> Algolia DocSearch 是通过在线爬虫抓取网站内容，然后再生成 搜索索引数据库的，首先需要确保 站点已部署并且可访问。 默认情况下它会定时自动爬取数据，也可以在 `Overview` 选项卡页面的右上角，点击 `restart clawling` 手动触发爬取。

好的，我尝试一下

**Comment by pengzhanbo** [comment]
> 现在最新的那个编译好像还会报错 🤔
> 
> ```
> [Vue warn]: Invalid watch source:  { open: false } A watch source can only be a getter/effect function, a ref, a reactive object, or an array of these types.
> ```

最近我在频繁更新调整主题，有些细节和警告可能会稍有疏漏

**Comment by huankong233** [comment]
> > ```js
> >         recordProps: {
> >             lvl0: {
> >               selectors: ".sidebar-item.is-active",
> >               defaultValue: "Documentation",
> >             },
> >             lvl1: ".content-container h1",
> >             lvl2: ".content-container h2",
> >             lvl3: ".content-container h3",
> >             lvl4: ".content-container h4",
> >             lvl5: ".content-container h5",
> >             lvl6: ".content-container h5",
> >             content: ".content-container p, .content-container li",
> >           },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这部分的内容中， 替换内容为
> > ```js
> >       recordProps: {
> >             lvl1: ".plume-theme-content h1",
> >             content: ".plume-theme-content p, .plume-theme-content li",
> >             lvl0: {
> >               selectors: "p.sidebar-heading.active",
> >               defaultValue: "Documentation",
> >             },
> >             lvl2: ".plume-theme-content h2",
> >             lvl3: ".plume-theme-content h3",
> >             lvl4: ".plume-theme-content h4",
> >             lvl5: ".plume-theme-content h5",
> >             lang: "",
> >             tags: {
> >               defaultValue: ["v2"],
> >             },
> >           },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Algolia DocSearch 是通过在线爬虫抓取网站内容，然后再生成 搜索索引数据库的，首先需要确保 站点已部署并且可访问。 默认情况下它会定时自动爬取数据，也可以在 `Overview` 选项卡页面的右上角，点击 `restart clawling` 手动触发爬取。
> 
> 好的，我尝试一下

好像不行（，我已经部署成功而且可以访问了啊，奇怪了

**Comment by pengzhanbo** [comment]
我看配置的其他部分没有什么问题， 或许检查下你的 `Index` 名是否正确， 是否是配置了 `index prefix` 导致了 名称没有匹配等。

**Comment by huankong233** [comment]
> 我看配置的其他部分没有什么问题， 或许检查下你的 `Index` 名是否正确， 是否是配置了 `index prefix` 导致了 名称没有匹配等。

![image](https://github.com/pengzhanbo/vuepress-theme-plume/assets/49610758/cbaf907c-3d48-4026-a8c5-1f474af8a370)

是huankong啊

**Comment by pengzhanbo** [comment]
看起来你不是访问的这个地址： https://crawler.algolia.com/admin/crawlers/

**Comment by huankong233** [comment]
> > 我看配置的其他部分没有什么问题， 或许检查下你的 `Index` 名是否正确， 是否是配置了 `index prefix` 导致了 名称没有匹配等。
> 
> ![image](https://private-user-images.githubusercontent.com/49610758/292829485-cbaf907c-3d48-4026-a8c5-1f474af8a370.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1Nzc0MzEsIm5iZiI6MTcwMzU3NzEzMSwicGF0aCI6Ii80OTYxMDc1OC8yOTI4Mjk0ODUtY2JhZjkwN2MtM2Q0OC00MDI2LWE4YzUtMWY0NzRhZjhhMzcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDA3NTIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2MTBhZDI4YTQ3MmRhOTBlZTdmZGQ1YmFjOGRkOWM0NzhiMDZkZTM5ZmNkMDJjMTg0YWUwZjhjZGQzMWZhMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TlpsAgHt8_7L_Li9OLfrqQlQVEKMimIREWnttwJDhC4)
> 
> 是huankong啊🤔🤔🤔

![image](https://github.com/pengzhanbo/vuepress-theme-plume/assets/49610758/16f62c7f-ca4a-42db-8ee0-cc6fc786ac55)

🤔🤔🤔

**Comment by huankong233** [comment]
> 看起来你不是访问的这个地址： https://crawler.algolia.com/admin/crawlers/

![image](https://github.com/pengzhanbo/vuepress-theme-plume/assets/49610758/79b9b55f-4077-41f2-86a6-f9752c50f6e4)

一样都是huankong

**Comment by pengzhanbo** [comment]
是 `.plume-content`，笑死，我的配置也忘改了。

**Comment by huankong233** [comment]
> 是 `.plume-content`，笑死，我的配置也忘改了。

我就说不对嘛 😂

**Comment by huankong233** [comment]
> > 是 `.plume-content`，笑死，我的配置也忘改了。
> 
> 我就说不对嘛 😂

但是记录还是空的（）

**Comment by pengzhanbo** [comment]
```js
new Crawler({
  rateLimit: 8,
  startUrls: ["https://pengzhanbo.cn/"],
  renderJavaScript: false,
  sitemaps: ["https://pengzhanbo.cn//sitemap.xml"],
  ignoreCanonicalTo: true,
  discoveryPatterns: ["https://pengzhanbo.cn/**"],
  schedule: "at 02:00 every 1 day",
  actions: [
    {
      indexName: "pengzhanbo",
      pathsToMatch: ["https://pengzhanbo.cn/**"],
      recordExtractor: ({ helpers }) => {
        return helpers.docsearch({
          recordProps: {
            lvl1: ".plume-content h1",
            content: ".plume-content p, .plume-content li",
            lvl0: {
              selectors: "p.sidebar-heading.active",
              defaultValue: "Documentation",
            },
            lvl2: ".plume-content h2",
            lvl3: ".plume-content h3",
            lvl4: ".plume-content h4",
            lvl5: ".plume-content h5",
            lang: "",
            tags: {
              defaultValue: ["v2"],
            },
          },
          aggregateContent: true,
          recordVersion: "v3",
        });
      },
    },
  ],
  initialIndexSettings: {
    pengzhanbo: {
      attributesForFaceting: ["type", "lang", "language", "version"],
      attributesToRetrieve: [
        "hierarchy",
        "content",
        "anchor",
        "url",
        "url_without_anchor",
        "type",
      ],
      attributesToHighlight: ["hierarchy", "hierarchy_camel", "content"],
      attributesToSnippet: ["content:10"],
      camelCaseAttributes: ["hierarchy", "hierarchy_radio", "content"],
      searchableAttributes: [
        "unordered(hierarchy_radio_camel.lvl0)",
        "unordered(hierarchy_radio.lvl0)",
        "unordered(hierarchy_radio_camel.lvl1)",
        "unordered(hierarchy_radio.lvl1)",
        "unordered(hierarchy_radio_camel.lvl2)",
        "unordered(hierarchy_radio.lvl2)",
        "unordered(hierarchy_radio_camel.lvl3)",
        "unordered(hierarchy_radio.lvl3)",
        "unordered(hierarchy_radio_camel.lvl4)",
        "unordered(hierarchy_radio.lvl4)",
        "unordered(hierarchy_radio_camel.lvl5)",
        "unordered(hierarchy_radio.lvl5)",
        "unordered(hierarchy_radio_camel.lvl6)",
        "unordered(hierarchy_radio.lvl6)",
        "unordered(hierarchy_camel.lvl0)",
        "unordered(hierarchy.lvl0)",
        "unordered(hierarchy_camel.lvl1)",
        "unordered(hierarchy.lvl1)",
        "unordered(hierarchy_camel.lvl2)",
        "unordered(hierarchy.lvl2)",
        "unordered(hierarchy_camel.lvl3)",
        "unordered(hierarchy.lvl3)",
        "unordered(hierarchy_camel.lvl4)",
        "unordered(hierarchy.lvl4)",
        "unordered(hierarchy_camel.lvl5)",
        "unordered(hierarchy.lvl5)",
        "unordered(hierarchy_camel.lvl6)",
        "unordered(hierarchy.lvl6)",
        "content",
      ],
      distinct: true,
      attributeForDistinct: "url",
      customRanking: [
        "desc(weight.pageRank)",
        "desc(weight.level)",
        "asc(weight.position)",
      ],
      ranking: [
        "words",
        "filters",
        "typo",
        "attribute",
        "proximity",
        "exact",
        "custom",
      ],
      highlightPreTag: '<span class="algolia-docsearch-suggestion--highlight">',
      highlightPostTag: "</span>",
      minWordSizefor1Typo: 3,
      minWordSizefor2Typos: 7,
      allowTyposOnNumericTokens: false,
      minProximity: 1,
      ignorePlurals: true,
      advancedSyntax: true,
      attributeCriteriaComputedByMinProximity: true,
      removeWordsIfNoResults: "allOptional",
    },
  },
  appId: "xxx",
  apiKey: "xxxx",
});
```

这是我目前的配置

**Comment by pengzhanbo** [comment]
![image](https://github.com/pengzhanbo/vuepress-theme-plume/assets/16745751/4d28ed93-6632-4da0-abf2-bd814d27f8a1)
试试在 run test 中 访问下你的站点，看看是否获取到的内容是最新的。 也有可能是DNS的影响， algolia 服务器访问到旧资源

**Comment by huankong233** [comment]
> ![image](https://private-user-images.githubusercontent.com/16745751/292832467-4d28ed93-6632-4da0-abf2-bd814d27f8a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1Nzg0NTIsIm5iZiI6MTcwMzU3ODE1MiwicGF0aCI6Ii8xNjc0NTc1MS8yOTI4MzI0NjctNGQyOGVkOTMtNjYzMi00ZGEwLWFiZjItYmQ4MTRkMjdmOGExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDA4MDkxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViZGUxNmZhMWZmODkwODkxN2Y2YWE5MjY2OGE3OGFlNzFmODI1Yjk5NzlhZmZmMGJiY2ZkYmZmNGRiZjA3ZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F7_od0yGOj0dnq2iOsXyo6YNdrVZjObhHVTsyW6pYW4) 试试在 run test 中 访问下你的站点，看看是否获取到的内容是最新的。 也有可能是DNS的影响， algolia 服务器访问到旧资源

![image](https://github.com/pengzhanbo/vuepress-theme-plume/assets/49610758/5b0516b5-77fa-4a56-a2fd-7e1e297ae709)

然后替换了一下你的那个配置，ba报错了

![image](https://github.com/pengzhanbo/vuepress-theme-plume/assets/49610758/0212e9a2-8fa3-4c3a-830d-21b51b0caa89)

**Comment by huankong233** [comment]
> > ![image](https://private-user-images.githubusercontent.com/16745751/292832467-4d28ed93-6632-4da0-abf2-bd814d27f8a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1Nzg0NTIsIm5iZiI6MTcwMzU3ODE1MiwicGF0aCI6Ii8xNjc0NTc1MS8yOTI4MzI0NjctNGQyOGVkOTMtNjYzMi00ZGEwLWFiZjItYmQ4MTRkMjdmOGExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDA4MDkxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViZGUxNmZhMWZmODkwODkxN2Y2YWE5MjY2OGE3OGFlNzFmODI1Yjk5NzlhZmZmMGJiY2ZkYmZmNGRiZjA3ZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F7_od0yGOj0dnq2iOsXyo6YNdrVZjObhHVTsyW6pYW4) 试试在 run test 中 访问下你的站点，看看是否获取到的内容是最新的。 也有可能是DNS的影响， algolia 服务器访问到旧资源
> 
> ![image](https://private-user-images.githubusercontent.com/49610758/292832919-5b0516b5-77fa-4a56-a2fd-7e1e297ae709.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1Nzg3MDEsIm5iZiI6MTcwMzU3ODQwMSwicGF0aCI6Ii80OTYxMDc1OC8yOTI4MzI5MTktNWIwNTE2YjUtNzdmYS00YTU2LWEyZmQtN2UxZTI5N2FlNzA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDA4MTMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3YzkzMjU5MjFmNDI4MmY3YjUyZjc2NDFkMWM0ZTlmMWQ4ZTlkYWI4ZDM3YTk2YWYzMzJmZWRhMDc2NjBkMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nhKQD1W1qvnOo-jM28nrCHBBn9S2pF6TBpQ6lgKU3MI)
> 
> 然后替换了一下你的那个配置，报错了
> 
> ![image](https://private-user-images.githubusercontent.com/49610758/292833259-0212e9a2-8fa3-4c3a-830d-21b51b0caa89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1Nzg3MDEsIm5iZiI6MTcwMzU3ODQwMSwicGF0aCI6Ii80OTYxMDc1OC8yOTI4MzMyNTktMDIxMmU5YTItOGZhMy00YzNhLTgzMGQtMjFiNTFiMGNhYTg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDA4MTMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlZWRhZTQ5YjgwODBkMTRjNWUwODY0NDhmMjFmZjRhN2UyNDBhYzYxOGM2ZmM5MTE1MWU3NGEyZWExZWYzNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UUvHlbb_MgBV9p9hEN1QqYB5L8J_7DecKzNctyFJEUo)

替换了之后，依旧是空 （

**Comment by pengzhanbo** [comment]
![image](https://github.com/pengzhanbo/vuepress-theme-plume/assets/16745751/68db9ac2-1cab-4c3b-984f-5fbb90980c12)
一般来说替换这部分就可以了。

**Comment by pengzhanbo** [comment]
missing records 说明了 algolia 没有访问到页面，可能问题出在这里了。

**Comment by huankong233** [comment]
> missing records 说明了 algolia 没有访问到页面，可能问题出在这里了。

然后我重新索引了一下还是没有，要不我把号给你😂

**Comment by pengzhanbo** [comment]
好，你加我 QQ 吧。 942450674

**Comment by huankong233** [comment]
bug 已修复

**Comment by SmartDengC** [comment]
@huankong233 你好，你能不能粘一下最终成功的 new Crawler({})内容，现在能够爬到内容，但是搜索框下面的搜索结果不能点击跳转。

**Comment by SmartDengC** [comment]
简单用cursor写了一个只有搜索框的界面，能够正常搜索、跳转，说明爬虫爬的数据没问题，大概率是项目问题。

![Image](https://github.com/user-attachments/assets/71cd68fb-4c2a-4de9-8b36-d0613aef54c2)

**Comment by pengzhanbo** [comment]
@SmartDengC 不要在已关闭许久的 issue 中回复新的问题，请通过提交新的 issue 的方式。一般我不会看已关闭的 issue 的。
