### ISSUE TITLE
[Bug] notes配置问题

### ISSUE THREAD

**Issue by binjoo** [pengzhanbo/vuepress-theme-plume#272]
### 检查清单

- [X] 我正在使用**LTS**版本的Node.js。
- [X] 我正在使用 **最新 v2 版本** 的 VuePress 和 VuePress 官方插件。
- [X] 我正在使用此仓库中的 **最新版本** 的 vuepress-theme-plume 及其所有插件。
- [X] 我按照文档操作，并仔细检查了我的配置。

### 包名

vuepress-theme-plume

### 你正在使用哪个操作系统？

- [ ] macOS
- [X] Windows
- [ ] Linux

### 描述该错误

![image](https://github.com/user-attachments/assets/d3ff4e7c-3634-4d1e-b088-5c81fdf18d5e)
![image](https://github.com/user-attachments/assets/6fb1da5a-f57f-4925-9b58-4b1408af6334)

不知道是不是我使用错误，我的理解这个配置应该是出现红框内的菜单，而不是出现重复的。

### 附加上下文

![image](https://github.com/user-attachments/assets/ea3b2552-4cd4-4e83-bcb9-82ca1fb9edff)

**Comment by pengzhanbo** [comment]
![1728743266825](https://github.com/user-attachments/assets/cecf6f17-762b-4ffb-abc0-91619bcd5020)

```diff
 sidebar: [
   {
     text: 'Java',
+    prefix: 'java',
     link: '/tech/java/',
     items: 'auto',
   },
   {
     text: 'Docker',
+    prefix: 'docker',
     link: '/tech/docker/'
     items: 'auto',
   }
 ]
```

需要使用 [`prefix`](https://theme-plume.vuejs.press/guide/document/#%E5%85%B3%E4%BA%8E-prefix) 来控制 items 读取的是 哪个文件夹下的。

**Comment by binjoo** [comment]
确实可以了，看来还是我没看明白文档，谢谢。
