### ISSUE TITLE
[Feature Request] frontmatter的全局设置

### ISSUE THREAD

**Issue by binjoo** [pengzhanbo/vuepress-theme-plume#279]
### 检查清单

- [X] 我搜索了现有问题，没有其他人请求类似功能。
- [X] 我认为25%以上的用户对此功能持积极态度。

### 描述该功能

**frontmatter**的*readingTime*、*createTime*等设置，是否可以加在`config.js`或者`plume.config.js`中作为全局的设置，而不是每个md文件都做设置。

### 附加上下文

五

**Comment by pengzhanbo** [comment]
`readingTim` 可以通过 `plugins.readingTime: false` 全局关闭。 
`createTime` 总是存在的，即使通过 `autoFrontmatter.createTime: false` 关闭自动生成，在主题内容依然会读取文件创建时间 作为文章排序依据。我认为总是显示 `createTime` 并无不妥。
其它的如 `outline`/ `prev` / `next` / `lastUpdated` / `contributors` / `editLink` / `externalLinkIcon` 等，都在 [主题配置](https://theme-plume.vuejs.press/config/basic/#locale-%E9%85%8D%E7%BD%AE) 找到对应的全局设置。

**Comment by binjoo** [comment]
其他的我明白了，对于`createTime`，我并不是说要去除这个属性，而是说在界面上不需要显示。
作为文档来说，个人觉得`createTime`可有可无，有一个`lastUpdated `就足够了。
