### ISSUE TITLE
[Feature Request] 添加公告功能

### ISSUE THREAD

**Issue by wu-clan** [pengzhanbo/vuepress-theme-plume#280]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

公告可以给用户带来很明显的感知性通知

**Comment by pengzhanbo** [comment]
公告这个功能我有考虑过实现，但目前我没有考虑清楚的是，如何让保证用户能够比较简单的方式进行配置，同时能够满足比较灵活的完全自定义的需求场景。对于灵活的自定义的场景，我不希望要求让用户在 配置文件里面写纯字符串的 html 内容，这太折磨了，因此需要找到其他替代方案。

**Comment by wu-clan** [comment]
md 本质上也支持 HTML 吧，或许只要支持 md 格式，用户写什么都行，可以提供一个顶部或者悬浮窗选择，如果悬浮窗可以加位置和宽高参数

**Comment by pengzhanbo** [comment]
我考虑过以下两种自定义方案：

1. 由用户注册一个 特殊的全局组件 `<BulletinBoard />`，用户在其中编写公告内容，添加交互等。这种方式是最灵活的，当然也存在相对高一点的使用门槛。

2. 添加一个特殊的 markdown 文件 `_bulletinBoard.md`，用户在其中编写内容。这种方式其实也相当于第一种，而且用户如果了解 markdown 文件其实也是一个 vue 组件，那么保持灵活的同时，还能使用 md 语法，还可以在里面写 `<script setup>`，当然门槛也会低一些。

**Comment by wu-clan** [comment]
全局组件看起来更加规范，但是如果是一个全局组件，那公告是在哪里都能配置的吗？但公告应该是一个全局的唯一的东西

**Comment by wu-clan** [comment]
或许可以像主页一样，固定到哪里？

**Comment by pengzhanbo** [comment]
计划中的 公告配置 分为两个步骤：

1. 在 主题配置中声明 启用公告，同时支持配置 公告位置、弹出公告按钮位置、显示在哪些页面等信息；
2. 编写 公告组件，主题提供一个 公告容器组件，可以在里面自定义 内容 和 按钮样式等信息。 或许还可以结合 上述的两个方案，也支持在外部的 `_bulletinBoard.md` 编写公告内容，由主题在内部完成组合。

不过我也还没有完全设想好整个流程。

**Comment by wu-clan** [comment]
Amazing, when will the next version be released?

**Comment by wu-clan** [comment]
预计何时发布此版本呢？
