### ISSUE TITLE
[Bug] details和code-tabs嵌套使用问题

### ISSUE THREAD

**Issue by Jackpanger** [pengzhanbo/vuepress-theme-plume#283]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest version** of vuepress-theme-plume and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.

### Package name

vuepress-theme-plume

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

以下两种情况结果有些疑惑：
1. 开头使用两个:::，结尾使用一个:::：
```markdown
    ::: details Solution
    There are several things to note
    
    ::: code-tabs
    @tab java
    ```java
    public String reorganizeString(String s) {
    }
    ```
    
    我想在这写一些东西
    :::

```

实际呈现效果：
![1728873426639](https://github.com/user-attachments/assets/8910a120-f38a-4a71-97bd-50024800eefd)
**“我想在这写一些东西”被吞。**

3. 开头使用两个:::，结尾使用两个:::：
```markdown
    ::: details Solution
    There are several things to note
    
    ::: code-tabs
    @tab java
    ```java
    public String reorganizeString(String s) {
    }
    ```
    :::
    我想在这写一些东西
    :::
```
实际呈现效果：
![WX20241013-203902@2x](https://github.com/user-attachments/assets/3acd6457-7454-4771-bdd5-362603f772f0)
**“我想在这写一些东西”被移到了details外面，未实现嵌套。**

### Additional context

_No response_

**Comment by pengzhanbo** [comment]
多个容器嵌套的时候，要注意 `:` 的数量，一般来说， 外层的 `:` 的数量必须多于内层 `:` 的数量。
比如 details 内嵌套 code-tabs ，那么 外层 details  应该写为 `:::: details` ，内层 code-tabs 写为 `::: code-tabs`

````md
:::: details

There are several things to note
    
::: code-tabs

@tab java
```java
public String reorganizeString(String s) {
}
```
:::

我想在这写一些东西

::::
````

嵌套时，外层的 `:` 数量必须多于内层的 `:` 数量。

**Comment by Jackpanger** [comment]
原来是这样，感谢！
