### ISSUE TITLE
[Feature Request] 文档增加标签功能

### ISSUE THREAD

**Issue by binjoo** [pengzhanbo/vuepress-theme-plume#285]
### 检查清单

- [X] 我搜索了现有问题，没有其他人请求类似功能。
- [X] 我认为25%以上的用户对此功能持积极态度。

### 描述该功能

查看文档中的配置，发现只有博客类型的文章才有`tags`功能，但是作为**文档/知识笔记**类型的文章，也是很需要标签。
如果标签里用的好，还可以形成**关系图谱**，能够更加便捷的找到相关联的其他文章。

例如我有若干篇菜谱文章，里面都涉及到了*鸡蛋*，那么我可以根据给出的标签关系图谱找到当前阅读文章中与*鸡蛋*、*韭菜*相关的其他文章。

![image](https://github.com/user-attachments/assets/5f193ca3-75d0-4b01-a9c9-54e7c348af65)

这样的标签关系图谱，对于知识花园来说非常有用。

**Comment by pengzhanbo** [comment]
我不会在主题中实现这样的标签关系图谱，这需要引入 `d3` 或 `chartjs` 等图表依赖作为默认依赖，这在我看来是非必要的，而且我认为绝大多数文档站点也不需要生成这样的标签关系图，它除了看起来挺“酷”之外，对于交互体验和快速搜索并没有带来多少的改进。

主题可能会做的，是在文章末尾列出当前 note 下的其他拥有相同标签的相关文章 （但这又与侧边栏导航所起的功能有所重合）。这所实现的功能，跟我在
[discussions#111](https://github.com/pengzhanbo/vuepress-theme-plume/discussions/111#discussioncomment-10927514) 中关于 博客的相关文章 的功能是类似的。
在我看来属于是分散注意力的功能，可能会做，但优先级不会高。
