### ISSUE TITLE
[Bug] 今天更新到新版本就报错了，随后我创建了一个新项目打开也报错

### ISSUE THREAD

**Issue by dubaomin1999** [pengzhanbo/vuepress-theme-plume#291]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest version** of vuepress-theme-plume and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.

### Package name

vuepress-theme-plume

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

启动正常，浏览器打开后，命令行报错（node：v20.12.2；pnpm：v9.0.6）

**Comment by pengzhanbo** [comment]
这个是 sass 发出的弃用警告信息，sass 将在 3.0.0 完全删除 `@import` 和 模块导入全局内置函数，它从 1.80.0 版本开始加入这个弃用警告。

但这个弃用警告并不会影响主题的正常使用。

我会先在主题中 静默这个弃用警告，后续再去调整更新 `@vuepress/plugin-sass-palette` 的相关代码。
