### ISSUE TITLE
[Bug]现在是否支持在网站的所有页面添加一个统一的footer页面

### ISSUE THREAD

**Issue by somta** [pengzhanbo/vuepress-theme-plume#296]
### 检查清单

- [X] 我正在使用**LTS**版本的Node.js。
- [X] 我正在使用 **最新 v2 版本** 的 VuePress 和 VuePress 官方插件。
- [X] 我正在使用此仓库中的 **最新版本** 的 vuepress-theme-plume 及其所有插件。
- [X] 我按照文档操作，并仔细检查了我的配置。

### 包名

vuepress-theme-plume

### 你正在使用哪个操作系统？

- [ ] macOS
- [ ] Windows
- [ ] Linux

### 描述该错误

现在是否支持在网站的所有页面添加一个统一的footer页面，引入下面所示

![image](https://github.com/user-attachments/assets/804c8dc3-9c96-4795-95ef-88533258e1de)

**Comment by pengzhanbo** [comment]
设置 [footer](https://theme-plume.vuejs.press/config/basic/#footer) 为 `false` 。使用 [布局插槽 > layout-bottom](https://theme-plume.vuejs.press/guide/layout-slots/#%E9%80%9A%E7%94%A8%E6%8F%92%E6%A7%BD) 自行编写 footer。
