### ISSUE TITLE
[Bug] permalink的缓存是在那里的，手动改后一直无法生效

### ISSUE THREAD

**Issue by somta** [pengzhanbo/vuepress-theme-plume#297]
### 检查清单

- [X] 我正在使用**LTS**版本的Node.js。
- [X] 我正在使用 **最新 v2 版本** 的 VuePress 和 VuePress 官方插件。
- [X] 我正在使用此仓库中的 **最新版本** 的 vuepress-theme-plume 及其所有插件。
- [X] 我按照文档操作，并仔细检查了我的配置。

### 包名

vuepress-theme-plume

### 你正在使用哪个操作系统？

- [ ] macOS
- [X] Windows
- [ ] Linux

### 描述该错误

![image](https://github.com/user-attachments/assets/9ed0ce24-49ec-4edf-8d36-a8f9d56f8d34)

**Comment by pengzhanbo** [comment]
当前 vuepress 的 permalink 不支持 `/random` 这种写法，要么 结尾是 `random.html`，要么结尾是 `/random/` 。 你的这个需求在 `vuepress` 有一个 PR Draft 在做这个事情，但遇到了一些问题还没有继续推进下去。
