### ISSUE TITLE
[Bug]想通过插槽，在文档侧边栏的最上面加一些信息，结果页面混乱了

### ISSUE THREAD

**Issue by somta** [pengzhanbo/vuepress-theme-plume#301]
### 检查清单

- [X] 我正在使用**LTS**版本的Node.js。
- [X] 我正在使用 **最新 v2 版本** 的 VuePress 和 VuePress 官方插件。
- [X] 我正在使用此仓库中的 **最新版本** 的 vuepress-theme-plume 及其所有插件。
- [X] 我按照文档操作，并仔细检查了我的配置。

### 包名

vuepress-theme-plume

### 你正在使用哪个操作系统？

- [ ] macOS
- [X] Windows
- [ ] Linux

### 描述该错误

需求：想通过插槽，在文档侧边栏的最上面加一些信息
1.添加插槽内容
`<script setup>
import { Layout } from 'vuepress-theme-plume/client'
</script>

<template>
  <Layout>
    <template #sidebar-nav-before>
      <div class="custom-content">
        自定义内容。。。。。
      </div>
    </template>
  </Layout>
</template>

<style>
.custom-content {
  //width: 100%;
  background-color: red;
}
</style>`

2.根据文档在client.ts中添加了组件信息，如下
 layouts:{
        SponsorSlot,
    },
结果发现页面没有任何变化，插槽内容也没有更新到

3.后通过如下方式添加，但是页面错乱了
` layouts:{
        Layout: () => h(Layout, null, {
            'sidebar-nav-before': () => h(SponsorSlot),
        })
    },`
![image](https://github.com/user-attachments/assets/c10e0c5f-971d-402b-8079-271f01769f77)

**Comment by pengzhanbo** [comment]
因为你的两种写法都写错了。

你的两种写法都没有根据 [文档](http://localhost:8080/guide/layout-slots/#%E4%BD%BF%E7%94%A8) 进行。

```ts
layouts:{
  SponsorSlot,
},
```
这样做只
是注册了一个自定义布局。而主题需要的是一个 名为 Layout 的布局组件。

（我不知道你在 SponsorSlot 组件写了什么，但是看你的截图大概能猜到 SponsorSlot 中引入了 Layout 组件）

你应该这么写：

```ts
layouts:{
  Layout: SponsorSlot,
},
```

而第二种方式中，假设我伤处的猜测成立，（SponsorSlot 中引入了 Layout 组件）
```
layouts:{ Layout: () => h(Layout, null, { 'sidebar-nav-before': () => h(SponsorSlot), }) },
```

那出现截图中的情况并不奇怪。这相当于在 sidebar-nav-before 这个插槽中又引入了整个 Layout 组件，变成了 Layout 中嵌套 Layout  的情况。

**Comment by somta** [comment]
SponsorSlot里面是直接复制的这里的代码

![image](https://github.com/user-attachments/assets/d45267b5-549e-4dee-8a01-aeee574aadce)

下面这样写的效果是什么？
layouts:{
  Layout: SponsorSlot,
},

**Comment by somta** [comment]
我好像理解了，通过下面的代码是定义一个全新的layout
layouts:{
Layout: SponsorSlot,
},

如果只是要在预置的插槽里面插入东西，就不能在vue里面引入layout组件，，然后插入的方式要使用下面的方式
 Layout: () => h(Layout, null, {
      'page-bottom': () => h(CustomContent),
    }),
不知道我理解的是否正确

**Comment by pengzhanbo** [comment]
两种写法其实是等价的，都是使用一个新的 Layout 组件覆盖 主题传给 vuepress 的 Layout 组件。只是一个是用 vue 的组件形式，一个是用 渲染函数 形式。

**Comment by somta** [comment]
layouts:{
Layout: SponsorSlot,
},这种是将整个layout全部覆盖了

**Comment by somta** [comment]
layouts:{
Layout: SponsorSlot,
},
上面这种应该是整个layout都覆盖了


Layout: () => h(Layout, null, {
'page-bottom': () => h(CustomContent),
}),

**Comment by somta** [comment]
layouts:{
Layout: SponsorSlot,
},
上面这种应该是整个layout都覆盖了

Layout: () => h(Layout, null, {
'page-bottom': () => h(CustomContent),
}),
这种应该还是原来的layout，只是覆写了原来layout里面的插槽
因为两种测试下来效果不一样的

**Comment by pengzhanbo** [comment]
哥们，都是一样的，你可以认为 把  vue 组件编译后就是 类似于 `h()` 的形式。
