### ISSUE TITLE
[Feature Request] Frontmatter对本文在sidebar的显示控制

### ISSUE THREAD

**Issue by bigtomcat6** [pengzhanbo/vuepress-theme-plume#307]
### 检查清单

- [X] 我搜索了现有问题，没有其他人请求类似功能。
- [x] 我认为25%以上的用户对此功能持积极态度。

### 描述该功能

现在遇到一个问题：当我在items: 'auto'的情况下有README.md或者index.md，在侧边栏中会重复显示这个文件

需要一个frontmatter配置(index: boolean)，可以在[sidebar](items: 'auto')的情况下，控制这个文章是否在侧边栏中显示

**Comment by pengzhanbo** [comment]
这里不需要额外的控制。实际上这里的自动生成没有达到我的预期。
我虽然考虑到了 items: 'auto' 的场景，但是没有考虑到 在这一层级中当存在 `README.md` 时，应该将链接有条件的提升到上一级，形成： `{ link, items: 'auto' }` 的形式。这也导致 上述的 bug 的产生。
