### ISSUE TITLE
[Bug] 时间显示

### ISSUE THREAD

**Issue by Zqzqsb** [pengzhanbo/vuepress-theme-plume#317]
### 检查清单

- [X] 我正在使用**LTS**版本的Node.js。
- [X] 我正在使用 **最新 v2 版本** 的 VuePress 和 VuePress 官方插件。
- [X] 我正在使用此仓库中的 **最新版本** 的 vuepress-theme-plume 及其所有插件。
- [X] 我按照文档操作，并仔细检查了我的配置。

### 包名

vuepress-theme-plume

### 你正在使用哪个操作系统？

- [ ] macOS
- [ ] Windows
- [ ] Linux

### 描述该错误

时间渲染问题，之前报告过，在归档中仍然存在。
![image](https://github.com/user-attachments/assets/2cfdeb36-e666-4247-839e-57a4f1ad25e7)

**Comment by pengzhanbo** [comment]
我更好奇为什么会出现这个时间格式，主题内部从未采用此时间格式，仅使用了 时间戳 和 `YYYY-MM-DD hh:mm:ss` 这种形式。
