### ISSUE TITLE
[Feature Request]为contributors添加新特性

### ISSUE THREAD

**Issue by QiHuang02** [pengzhanbo/vuepress-theme-plume#319]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

# 请求为contributors添加图中这样的新特性：
![image](https://github.com/user-attachments/assets/90fbd3f4-f844-405f-a18e-027fbdfc0546)
在帮别人编写编写文档的时候遇到的感觉挺有意思的。
请求的新特性描述：可以显示贡献者的头像，然后点击名字或者头像可以跳转到贡献者的github主页或者其他自定义链接。同时该部分作为md的二级标题可以显示在此页`内容部分`。

**Comment by pengzhanbo** [comment]
这里实际上有比较麻烦的问题点。

我不能假定用户使用的 一定是 github ，还可能是其他的诸如 gitlab、gitee 等其他 git 服务。 这时候 其头像地址、跳转地址都将是不同的。而在 git 提交记录里面，我没记错的话，只有 用户名 和 用户邮箱 两个关键信息，但是否能够获取到   git 服务类型如 github、gitlab 等，我没有去研究过。

**Comment by pengzhanbo** [comment]
> 那可以做一个较为麻烦的处理嘛？比如预先定义一个全局的变量，手动配置其中需要的东西例如头像（的链接或者是博客本地图片）、需要跳转的链接

全局变量 是最糟糕的处理方式。

这块我需要 研究下方案和流程。将其作为一个可选的功能 来实现。
但毕竟大多数的文档 的 contributors 仅有原作者一人，保留两种方式作为可选是有必要的。

**Comment by QiHuang02** [comment]
> 全局变量 是最糟糕的处理方式。

我能理解！这确实是

> 这块我需要 研究下方案和流程。将其作为一个可选的功能 来实现。
> 
> 但毕竟大多数的文档 的 contributors 仅有原作者一人，保留两种方式作为可选是有必要的。

感谢，麻烦大佬了

**Comment by pengzhanbo** [comment]
这里的存在的问题比我一开始想的要复杂些。

用户在 git 设置的 用户名 和 邮箱 并不一定跟 git 服务上的一致，这会导致从记录中获取的用户名 生成的如 `https://github.com/username` 是不正确的。 这种情况下就需要 站点主题来维护一份 用户别名映射表，获取正确的用户名。

**Comment by QiHuang02** [comment]
> 这里的存在的问题比我一开始想的要复杂些。
> 
> 用户在 git 设置的 用户名 和 邮箱 并不一定跟 git 服务上的一致，这会导致从记录中获取的用户名 生成的如 `https://github.com/username` 是不正确的。 这种情况下就需要 站点配置中维护一份 用户别名映射表，获取正确的用户名。

也就是说实际上实现还是很麻烦，那还是暂时关闭这个issue吧？

**Comment by pengzhanbo** [comment]
> 也就是说实际上实现还是很麻烦，那还是暂时关闭这个issue吧？

先保留着吧，不过我暂时不会在本主题中实现这个功能，我可能需要先到上游的 `@vuepress/plugin-git` 中做一些更新调整，然后再回到主题实现这块功能。

**Comment by pengzhanbo** [comment]
https://github.com/vuepress/ecosystem/pull/283
