### ISSUE TITLE
代码演示 UI 小问题

### ISSUE THREAD

**Issue by shylock-wu** [pengzhanbo/vuepress-theme-plume#324]
### 检查清单

- [X] 我正在使用**LTS**版本的Node.js。
- [X] 我正在使用 **最新 v2 版本** 的 VuePress 和 VuePress 官方插件。
- [X] 我正在使用此仓库中的 **最新版本** 的 vuepress-theme-plume 及其所有插件。
- [X] 我按照文档操作，并仔细检查了我的配置。

### 包名

vuepress-theme-plume

### 你正在使用哪个操作系统？

- [X] macOS
- [ ] Windows
- [ ] Linux

### 描述该错误

问题：我在使用代码演示的时候发现了一个小小的 UI 问题，所以找到了[这里](https://github.com/pengzhanbo/vuepress-theme-plume/commit/cc9b5f8a40f502fa4d0fa7400e5807387445ee25#diff-9dd4ee29d77302cd85a1d79b906e511f367b816e4cbb8e6662e55e1a0a0016ecR250)
提问作者大大：为什么这里要使用`-13px`，vuepress-plugin-md-enhance 提供的 UI 是正常的。
从截图可以看到 padding 20px 正常撑开，但是，由于使用了`margin-bottom: -13px;`，导致内边距底部和其他三边不一致了，看起来有点奇怪🤔。所以如果作者对这里的设置是为了影响其他的地方，请告诉我这不是一个问题
![Image](https://github.com/user-attachments/assets/a57adb6a-00db-4613-8d43-07e113288f8a)

**Comment by pengzhanbo** [comment]
之前在做这块的 UI 调整时，如果不设置 -13px， 那么在展开后，代码块的底部会空白出一个高度为 13px 的区域，显得非常糟糕。 本来我是想在展开状态时再减去 13px 的，但是 由于 md-enhance 插件在这里做的是 js 动画，高度是计算后赋值，单用 css 不能改到位。因此直接粗暴的 -13px。 

由于 plugin-md-enhance 体积太大了，大到维护非常困难，我之前想去 提 PR 修改交互，但插件代码看得我无从下手，因此我也跟插件作者 Hope 讨论了拆分和迁移计划， 插件也正在做 拆分和迁移到 官方插件库 中，从进度上来说，已完成了 大约一半左右的工作。也鉴于此，我也暂时维持了 -13px 的方式去调整 UI。

未来 代码演示 这块也会拆分出来作为独立的插件使用，因此会在拆分完成后，主题重新接入新的插件，到时候再进行调整。
