### ISSUE TITLE
[Bug] 关于同一页面中 markdown 公式渲染过多导致切换深色模式出现性能下降的问题

### ISSUE THREAD

**Issue by Velvet0314** [pengzhanbo/vuepress-theme-plume#325]
### 检查清单

- [X] 我正在使用**LTS**版本的Node.js。
- [X] 我正在使用 **最新 v2 版本** 的 VuePress 和 VuePress 官方插件。
- [X] 我正在使用此仓库中的 **最新版本** 的 vuepress-theme-plume 及其所有插件。
- [X] 我按照文档操作，并仔细检查了我的配置。

### 包名

vuepress-theme-plume

### 你正在使用哪个操作系统？

- [ ] macOS
- [x] Windows
- [ ] Linux

### 描述该错误

如题，切换时会出现卡顿，博主大大有考虑进行一定的优化吗？

**Comment by pengzhanbo** [comment]
emmmm.... 实际上 外观切换是一个开销非常高的操作，因为这一步操作需要对当前页面的绝大多数元素进行动画过渡，涉及到的元素、属性会非常多。特别是一个内容比较多，结构复杂、元素节点数量多时，开销是非常夸张的。

可以参考这两篇文章：

[paco.me/writing/disable-theme-transitions](https://paco.me/writing/disable-theme-transitions)
[stackoverflow.com/a/16575811/11613622](https://stackoverflow.com/a/16575811/11613622)

主题对 外观切换的动画 是否依然采用当前的方案 也是出于 研究阶段，为此还提供了 [transition](https://theme-plume.vuejs.press/config/basic/#transition) 用于控制是否启用站点一些主要的动画。

对于 内容过多导致 切换卡顿，我当前是建议 关闭过渡动画的。

未来主题可能会使用 [View Transition API](https://developer.chrome.com/docs/web-platform/view-transitions?hl=zh-cn) 来实现过渡动画效果，从整个站点的角度来实现，而非对每个元素应用过渡动画。
