### ISSUE TITLE
写文章或文档是，支持指定每个文章的keyword 和descption，并生成到对应的静态文件中，便于seo爬取

### ISSUE THREAD

**Issue by somta** [pengzhanbo/vuepress-theme-plume#337]
### 检查清单

- [X] 我搜索了现有问题，没有其他人请求类似功能。
- [X] 我认为25%以上的用户对此功能持积极态度。

### 描述该功能

写文章或文档是，支持指定每个文章的keyword 和descption，并生成到对应的静态文件中，便于seo爬取

### 附加上下文

写文章或文档是，支持指定每个文章的keyword 和descption，并生成到对应的静态文件中，便于seo爬取

**Comment by pengzhanbo** [comment]
在有配置 hostname 的情况下，主题内置的 [seo 插件](https://theme-plume.vuejs.press/guide/seo/) 会为页面自动生成 [OGP](https://ogp.me/) 和 [JSON-LD](https://www.w3.org/TR/json-ld-api/) 等元信息，这些都是有助于 SEO 的。

对于 `descprition` 默认就是支持的，你在 页面的 frontmatter  中添加该字段即可。

对于 `keywords`，使用 [`frontmatter.head`](https://v2.vuepress.vuejs.org/zh/reference/frontmatter.html#head)  添加该字段即可。

```md
---
description: xxxxx
head:
  - - meta
    - name: keywords
      content: xxxxx
---
```
