### ISSUE TITLE
[Feature Request] markdown 自定义容器的 detail 类型支持默认展开

### ISSUE THREAD

**Issue by pecliu** [pengzhanbo/vuepress-theme-plume#344]
### 检查清单

- [X] 我搜索了现有问题，没有其他人请求类似功能。
- [X] 我认为25%以上的用户对此功能持积极态度。

### 描述该功能

https://theme-plume.vuejs.press/article/mcgayb5w/#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%87%E9%A2%98

目前自定义容器的detail默认都是折叠起来的。希望能有一个配置可以支持详情默认展开

### 附加上下文

<img width="557" alt="image" src="https://github.com/user-attachments/assets/d401ac84-18d7-4948-8f48-c4a06a1e2875">

**Comment by pengzhanbo** [comment]
自定义容器 details 的功能由 `@vuepress/plugin-markdown-hint` 插件实现，请在 [vuepress/ecosystem](https://github.com/vuepress/ecosystem) 提出 feature request。
