### ISSUE TITLE
[Feature Request] git committer 的配置支持动态映射

### ISSUE THREAD

**Issue by pecliu** [pengzhanbo/vuepress-theme-plume#349]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

最新版本下，如果用的不是 github 的仓库，那么 committer 的头像需要硬编码在代码里。
而实际场景往往团队维护人很多，来不及添加映射代码。 而团队成员的头像 url 又具备一定的正则共性。
希望能偶有办法直接动态转换 username 的 avatar 。 比如 avatar的地址其实是固定链接+username。在有新成员加入工程时可以自动转换头像地址

**Comment by pengzhanbo** [comment]
据我所了解的，在 git 主流的托管服务中，除了 github 的 头像与 username 有直接的关联关系外，gitee、gitlab、Bitbucket 等的 头像 有的是使用的 上传时生成的路径作为 头像地址，有的是使用 userid 等，与 username 没有直接关系。 这也是我没有在 `@vuepress/plugin-git` 中给 avatar 提供 模式匹配的原因。

**Comment by pecliu** [comment]
> 据我所了解的，在 git 主流的托管服务中，除了 github 的 头像与 username 有直接的关联关系外，gitee、gitlab、Bitbucket 等的 头像 有的是使用的 上传时生成的路径作为 头像地址，有的是使用 userid 等，与 username 没有直接关系。 这也是我没有在 `@vuepress/plugin-git` 中给 avatar 提供 模式匹配的原因。

嗯，我们是一个私有部署的 git，avatar 路径是可以根据 username 推断出来的

**Comment by pengzhanbo** [comment]
该功能需要等待一段时间，我会在 `vuepress/ecosystem` 仓库中进行相关的更新，然后再回到主题这边做更新适配。

**Comment by eastgold15** [comment]
[![image](https://github.com/user-attachments/assets/49e1d49e-de80-4494-83b7-0a4bbf873bba)](url)

**Comment by eastgold15** [comment]
感谢版主，热情，回复超快
