### ISSUE TITLE
[Bug] copyright 设置不起作用

### ISSUE THREAD

**Issue by frg2089** [pengzhanbo/vuepress-theme-plume#362]
### 检查清单

- [X] 我正在使用**LTS**版本的Node.js。
- [X] 我正在使用 **最新 v2 版本** 的 VuePress 和 VuePress 官方插件。
- [X] 我正在使用此仓库中的 **最新版本** 的 vuepress-theme-plume 及其所有插件。
- [X] 我按照文档操作，并仔细检查了我的配置。

### 包名

vuepress-theme-plume

### 你正在使用哪个操作系统？

- [ ] macOS
- [ ] Windows
- [ ] Linux

### 描述该错误

我在主题中这样配置 但它毫无作用 在页面上还是显示 CC-BY-4.0
```typescript
import { plumeTheme } from 'vuepress-theme-plume'

export default plumeTheme({
  // ...
  copyright: 'CC-BY-NC-SA-4.0',
  // ...
})
```

**Comment by pengzhanbo** [comment]
随下个版本一起修复。
