### ISSUE TITLE
[Bug]ThemeConfig 类中缺少 blog 和 article 字段

### ISSUE THREAD

**Issue by evanqhu** [pengzhanbo/vuepress-theme-plume#388]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest version** of vuepress-theme-plume and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.

### Package name

vuepress-theme-plume

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

根据文档描述，blog 和 article 配置项是可以在 plume.config.ts 中配置的，但是 defineThemeConfig 函数的参数类型 ThemeConfig 类缺少这两个字段

**Comment by pengzhanbo** [comment]
这两个字段参与了 站点初始化启动时，编译生成博客相关的页面，以及参与了 页面 frontmatter 的自动生成，对他们的修改进行热更新并不能重新触发这些编译相关的任务，因此将它们从 `ThemeConfig` 中移除了。
