### ISSUE TITLE
[Bug] markdown 和 html 中标签<em></em>内中文没有倾斜

### ISSUE THREAD

**Issue by fanwendi8** [pengzhanbo/vuepress-theme-plume#392]
### 检查清单

- [X] 我正在使用**LTS**版本的Node.js。
- [X] 我正在使用 **最新 v2 版本** 的 VuePress 和 VuePress 官方插件。
- [X] 我正在使用此仓库中的 **最新版本** 的 vuepress-theme-plume 及其所有插件。
- [X] 我按照文档操作，并仔细检查了我的配置。

### 包名

vuepress-theme-plume

### 你正在使用哪个操作系统？

- [ ] macOS
- [X] Windows
- [ ] Linux

### 描述该错误

在主题中任意中英混合语句中，增加 em 标签，可以明显发现问题。

在主题多个案例站点包括您的博客中都存在该问题。

![image](https://github.com/user-attachments/assets/39d41bca-7585-4975-9161-958f75bbb59c)

**Comment by fanwendi8** [comment]
另外一个文字排版建议，我注意到您 markdown 写作中有注意到，中英混合时，英文前后加空格的排版优化。但在中文和数字混合排版时，数字前后增加空格排版优化似乎存在遗漏。视觉效果有点拥挤，建议优化一下。

比较大范围的，每个 markdown 生成的页面信息中。
![image](https://github.com/user-attachments/assets/36807671-1856-4f9e-9388-10c4333530b0)

**Comment by fanwendi8** [comment]
> 另外一个文字排版建议，我注意到您 markdown 写作中有注意到，中英混合时，英文前后加空格的排版优化。但在中文和数字混合排版时，数字前后增加空格排版优化似乎存在遗漏。视觉效果有点拥挤，建议优化一下。
> 
> 比较大范围的，每个 markdown 生成的页面信息中。 ![image](https://private-user-images.githubusercontent.com/187466791/397910319-36807671-1856-4f9e-9388-10c4333530b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3NzA2ODUsIm5iZiI6MTczNDc3MDM4NSwicGF0aCI6Ii8xODc0NjY3OTEvMzk3OTEwMzE5LTM2ODA3NjcxLTE4NTYtNGY5ZS05Mzg4LTEwYzQzMzM1MzBiMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMVQwODM5NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNTRkN2Q2NzVkYjNjZTMyZjAyOGE0MDdkNzkyMTg2ZTRhM2ZjZmJkNGY3YjE1MDY0MDYyNTYzNGY3NGFiNmFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.VoXxI-P5alkr0TeNradeXmM08E22aoDA7davUTLtdYU)

[reading-time 插件](https://ecosystem.vuejs.press/zh/plugins/development/reading-time.html#%E5%9C%A8%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BE%A7%E8%8E%B7%E5%8F%96%E6%95%B0%E6%8D%AE) 结果没有问题，似乎版本原因？

![image](https://github.com/user-attachments/assets/16d4b3c3-055f-4f5e-a317-91a9366fa701)

**Comment by pengzhanbo** [comment]
对于字体，主题并没有设置采用哪个字体作为默认中文字体库。字体由 浏览器设置 -> 系统设置 所决定。

主题仅是对 字母、数字等使用了 `Inter` 字体。以及在中文时对一些标点符号做了字体规范化。其他的均是根据用户设备所决定。

当你发现在你的设备中没有显示 斜体。那说明你的设备所使用的默认字体不支持斜体。

**Comment by pengzhanbo** [comment]
关于 reading-time 显示比较紧凑，是因为早期版本 page-meta 显示了更多的信息，为了能够在一行中容纳下更多信息，因此特意裁剪了空格。现在的版本删除了一些不必要的 meta，但是还没有重新调整 reading-time 的排版。

**Comment by fanwendi8** [comment]
> 对于字体，主题并没有设置采用哪个字体作为默认中文字体库。字体由 浏览器设置 -> 系统设置 所决定。
> 
> 主题仅是对 字母、数字等使用了 `Inter` 字体。以及在中文时对一些标点符号做了字体规范化。其他的均是根据用户设备所决定。
> 
> 当你发现在你的设备中没有显示 斜体。那说明你的设备所使用的默认字体不支持斜体。

似乎出现了奇怪的问题，我开始认为是字体原因，后来测试发现不是，我只在使用 plume 主题的网站中，使用 em 标签或者markdown *  强调文本时，中文不会倾斜，其他网站或者其他 vuepress 主题（hope）都没有问题。

您在 plume 主题下 markdown 或者 em 标签字体均渲染正常吗？

**Comment by fanwendi8** [comment]
似乎出现了奇怪的问题，中文无法倾斜只在使用 plume 主题的网站出现，其他网站和其他 vuepress 主题（Hope）均可以倾斜，我的设备字体为电脑默认微软雅黑，支持斜体显示。现在没有问题的头绪，确认下，在您设备上主题中文的斜体显示都没有问题吗？

**Comment by pengzhanbo** [comment]
找到原因了，因为受到了 [font-synthesis](https://developer.mozilla.org/zh-CN/docs/Web/CSS/font-synthesis) 属性的影响，主题默认设置为了 `none`，禁止为不支持的字体，生成/合成 斜体/粗体，导致了此类问题。
我在下个版本调整下这个属性的值吧。

**Comment by fanwendi8** [comment]
好的，感谢帮助，同时期待下版本 sidebar 的更新。
