### ISSUE TITLE
detail详情

### ISSUE THREAD

**Issue by panxiao1** [pengzhanbo/vuepress-theme-plume#47]
<img width="989" alt="image" src="https://github.com/pengzhanbo/vuepress-theme-plume/assets/22336563/a47c2f0c-ccab-4d48-aa5d-6b6c13c6ad93">
<img width="794" alt="image" src="https://github.com/pengzhanbo/vuepress-theme-plume/assets/22336563/8460ce1b-3516-4535-93b8-0b3a08cb46a0">

我的样式错乱了，是为什么呢？

**Comment by pengzhanbo** [comment]
多个内容容器嵌套时，需要注意 `:` 的数量。

````md
:::: details
::: react-demo
``` js
// more
```
:::
::::
````

一般来说， `:` 的数量，从最外层到内层，是递减的。 这包括在写代码块如果有嵌套情况时，也是一样的：
````` md
```` md
``` ts
// more
```
````
`````

**Comment by panxiao1** [comment]
感谢，完美解决
