### ISSUE TITLE
notes 自动生成侧边栏问题

### ISSUE THREAD

**Issue by YuChenDayCode** [pengzhanbo/vuepress-theme-plume#57]
![image](https://github.com/pengzhanbo/vuepress-theme-plume/assets/19216741/92ef9fc2-58f3-4935-9187-ec0c748b6864)

大佬 这个设置为auto能生效吗？我配置了没成功，我看你参考代码也是写死的items

**Comment by pengzhanbo** [comment]
嗯，我重新验证了一下，在一次对 note 的调整更新中，与 `auto` 的规则产生了冲突，导致生成失败，这两天我解决下

**Comment by YuChenDayCode** [comment]
可以了！谢谢大佬

**Comment by pengzhanbo** [comment]
@YuChenDayCode 该问题已在新版本 `1.0.0-rc.43` 中修复
