### ISSUE TITLE
请问一下能不能同时开启blog和note，note如何配置

### ISSUE THREAD

**Issue by prayjourney** [pengzhanbo/vuepress-theme-plume#59]
你好作者，有两个问题麻烦解答一下
1.请问一下能不能同时开启blog和note，如何只开启其中的一个
2.如果能同时开启，那么如何开启note，或者说如何访问note呢，我想在导航栏上面添加note里面的内容，或者怎么样才能达到note的首页呢？下面是我的配置，java是note下面的一个文件夹，java里面有s1.md，s2.md，s3.md三个文档。
```js
export default defineUserConfig({
  // 请不要忘记设置默认语言
  lang: 'zh-CN',
  theme: plumeTheme({
    avatar: {
      name: '我的名字',
    },
    navbar: [
      { text: '首页', link: '/', icon: 'material-symbols:home-outline' },
      { text: '博客', link: '/blog/', icon: 'material-symbols:article-outline' },
      { text: 'notes', link: '/article/jgxe2m3y/', icon: 'material-symbols:favorite' },
      {
          text: '技术文档',
          icon: 'mdi:idea',
          items: [
            {
              text: 'Vuepress的主题',
              icon: 'icon-park-solid:theme',
              items: [
                {
                  text: 'plume主题',
                  link: '/vuepress-theme-plume/',
                  icon: 'mdi:paper-airplane',
                },
              ],
            },
            {
              text: 'Vuepress的插件',
              icon: 'mingcute:plugin-2-fill',
              items: [
                {
                  text: 'caniuse',
                  link: '/vuepress-plugin/caniuse/',
                  icon: 'pajamas:feature-flag',
                },
                {
                  text: 'blog-data',
                  link: '/vuepress-plugin/blog-data/',
                  icon: 'ic:baseline-post-add',
                },
                {
                  text: 'blog-data的文档',
                  link: '/article/lx20qn0j/',
                  icon: 'ic:baseline-post-add',
                }
              ],
            },
          ],
        }
    ],
    notes: {
      dir: '/notes/', 
      link: '/', 
      notes: [
        {
          dir: 'java', 
          link: '/java/',
          sidebar: [
            {
              text: '简介',
              icon: 'mdi:language-typescript',
              items: ['s1', 's2', 's3']
            }
          ]
        },
        {
          dir: 'kotlin',
          link: '/kotlin/',
          sidebar: [
            { 
              text: '简介',
              icon: 'mdi:language-typescript',
              items: ['s1', 'j2'] 
            }
          ]
        }
      ]
    }
  }),
  bundler: viteBundler(),
  title: 'test',
  description: '这是我的第一个 VuePress 站点',
})
```

**Comment by pengzhanbo** [comment]
blog 和  notes  默认就是同时开启的。

- [blog 配置](https://plume.pengzhanbo.cn/config/basic/#blog)
- [notes 配置](https://plume.pengzhanbo.cn/config/notes/)

假设你的 源文件目录为 `docs`

> 如何只开启其中的一个

- 比如 只启用 blog 功能，那就不要在 `docs/notes` 目录下创建 md 文件即可
- 比如 只启用 notes 功能， 那就直接把  `notes.dir` 配置为 `/` ，将你的整个 docs 目录作为 notes 目录，主题将不再把 docs 下的 任何 md 文件判断为 blog。

> 我想在导航栏上面添加note里面的内容，或者怎么样才能达到note的首页呢？

假设你的目录结构为:
```sh
docs/
├─ notes/
    ├─ java/
       ├─ s1.md
	   ├─ s2.md
       ├─ s3.md
```

由于你没有在 java 目录下创建 `README.md` 文件，因此该 note 没有默认首页。但是你可以将 `s1.md` 等其他任意文件当做你的首页。比如，你想把 `s1.md` 文件当做首页，当你启用 vuepress
你应该能够在 `s1.md` 文件的头部看到如下内容：
````md
---
title: java
createTime: xxxx
permalink: /java/xxxx/
---
````

其中， `permalink` 是主题自动生成的页面链接，你可以直接把这个链接复制，然后配置到 主题配置的 `navbar` 选项中。
```ts
theme: plumeTheme({
  navbar: [ { text: 'java', link: '/java/xxxx/' } ]
})
```

这样就能够在 导航栏中链接到 java note 了。

如果你在 `java/` 目录下创建了一个 `README.md` 文件，也是类似的，只是主题为这个文件生成的 `permalink` 为
`/java/` 看起来更符合 note 首页的链接。依然需要手动将其配置到 `navbar` 配置或者你期望的其它位置 进行跳转。

**Comment by prayjourney** [comment]
我已收到您的来信，谢谢！祝您生活愉快！

**Comment by prayjourney** [comment]
> blog 和 notes 默认就是同时开启的。
> 
> * [blog 配置](https://plume.pengzhanbo.cn/config/basic/#blog)
> * [notes 配置](https://plume.pengzhanbo.cn/config/notes/)
> 
> 假设你的 �源文件目录为 `docs`
> 
> > 如何只开启其中的一个
> 
> * 比如 只启用 blog 功能，那就不要在 `docs/notes` 目录下创建 md 文件即可
> * 比如 只启用 notes 功能， 那就直接把  `notes.dir` 配置为 `/` ，将你的整个 docs 目录作为 notes 目录，主题将不再把 docs 下的 任何 md 文件判断为 blog。
> 
> > 我想在导航栏上面添加note里面的内容，或者怎么样才能达到note的首页呢？
> 
> 假设你的目录结构为:
> 
> ```shell
> docs/
> ├─ notes/
>     ├─ java/
>        ├─ s1.md
> 	   ├─ s2.md
>        ├─ s3.md
> ```
> 
> 由于你没有在 java 目录下创建 `README.md` 文件，因此该 note 没有默认首页。但是你可以将 `s1.md` 等其他任意文件当做你的首页。比如，你想把 `s1.md` 文件当做首页，当你启用 vuepress 你应该能够在 `s1.md` 文件的头部看到如下内容：
> 
> ```
> ---
> title: java
> createTime: xxxx
> permalink: /java/xxxx/
> ---
> ```
> 
> 其中， `permalink` 是主题自动生成的页面链接，你可以直接把这个链接复制，然后配置到 主题配置的 `navbar` 选项中。
> 
> ```ts
> theme: plumeTheme({
>   navbar: [ { text: 'java', link: '/java/xxxx/' } ]
> })
> ```
> 
> 这样就能够在 导航栏中链接到 java note 了。
> 
> 如果你在 `java/` 目录下创建了一个 `README.md` 文件，也是类似的，只是主题为这个文件生成的 `permalink` 为 `/java/` 看起来更符合 note 首页的链接。依然需要手动将其配置到 `navbar` 配置或者你期望的其它位置 进行跳转。

懂了，多谢老哥，刚才试了一下，我觉得，这块需要添加一个点，就是，需要先去配置config，把目录这些配置好了之后，再去到对应的目录下创建md文档，这样生成的url就会按照规则配置的规则生成了，否则就是/article这种，感觉可以在文档里面说明一下。


多谢老哥，生活愉快😃🌈

**Comment by pengzhanbo** [comment]
> 我觉得，这块需要添加一个点，就是，需要先去配置config，把目录这些配置好了之后，再去到对应的目录下创建md文档，这样生成的url就会按照规则配置的规则生成了，否则就是/article这种，感觉可以在文档里面说明一下。

好，我补充完善下这块的文档。
