### ISSUE TITLE
按照步骤运行后报错啊

### ISSUE THREAD

**Issue by shylock-wu** [pengzhanbo/vuepress-theme-plume#61]
![CleanShot 2024-04-03 at 19 32 09@2x](https://github.com/pengzhanbo/vuepress-theme-plume/assets/73875874/3cd90877-e96d-4530-aca4-bb467d268c35)

很奇怪

**Comment by pengzhanbo** [comment]
因为你的 `.vuepress` 文件夹位置放错了， 根据你的 package.json 中的 `scripts` 配置，你的 `.vuepress` 英爱是放在 `docs` 目录下的，而不是与 `docs` 同级。

如果你想保持当前目录不变，你应该修改你的 `scripts` 命令：

```json
{
  "scripts": {
  	"dev": "vuepress dev docs --config .vuepress/config.ts",
    "build": "vuepress build docs --config .vuepress/config.ts"
  }
}
```

**Comment by shylock-wu** [comment]
hhh我看你写的文档就是以为在根目录下，因为我没看vuepress的官方文档 所以正常流程走下来就遇到这个问题了 感觉你可以说明一下
