### ISSUE TITLE
考虑给 dome 加一个全屏的功能吗，如果dome出现滚动条，不好查看

### ISSUE THREAD

**Issue by garmin21** [pengzhanbo/vuepress-theme-plume#62]
![image](https://github.com/pengzhanbo/vuepress-theme-plume/assets/51853339/9d37beb3-8777-4575-86e7-c3f338f8f43c)

**Comment by pengzhanbo** [comment]
demo 代码演示 功能是由 [vuepress-plugin-md-enhance](https://vuepress-theme-hope.github.io/v2/md-enhance/zh/guide/code/) 插件提供的支持。 主题通过内置该插件提供的 代码演示 功能，因此，如果你期望能实现 全屏查看 的功能，可以通过给 [vuepress-plugin-md-enhance](https://github.com/vuepress-theme-hope/vuepress-theme-hope/tree/main/packages/md-enhance/) 提出新的 [Feature Request](https://github.com/vuepress-theme-hope/vuepress-theme-hope/issues/new/choose)。
