### ISSUE TITLE
文章内一级标题不会显示右侧边栏

### ISSUE THREAD

**Issue by YTAZWC** [pengzhanbo/vuepress-theme-plume#63]
你好，请问一级标题是无法显示右侧边栏吗？
## MD文件
![image](https://github.com/pengzhanbo/vuepress-theme-plume/assets/151493883/e6f8c81e-94a1-478f-a510-28b18afaaedf)
## 效果显示
![Snipaste_2024-04-14_21-43-18](https://github.com/pengzhanbo/vuepress-theme-plume/assets/151493883/c143a3b6-e90a-45e3-b971-bba62ecdc262)

**Comment by pengzhanbo** [comment]
一级标题不会显示在 侧边栏的。 
因为 一级标题 的作用是 作为文章的大标题，而它在 `fronmatter.title` 中已进行配置。
因此，文章内容一般就不需要包含 一级标题 了，而是从 二级标题 开始，这也是大部分 md 写作时的通用规范了

**Comment by YTAZWC** [comment]
> 一级标题不会显示在 侧边栏的。 因为 一级标题 的作用是 作为文章的大标题，而它在 `fronmatter.title` 中已进行配置。 因此，文章内容一般就不需要包含 一级标题 了，而是从 二级标题 开始，这也是大部分 md 写作时的通用规范了

好的，还有一个问题想请教，就是我设置了base属性，然后导航栏的路径出现了问题，自动给我重复了两次base的路径，这种我该怎么解决呢？

配置文件如下：
![image](https://github.com/pengzhanbo/vuepress-theme-plume/assets/151493883/5d4b0656-db5d-40b7-8072-c0a8e596f481)
dev后，鼠标悬停放在首页，左下角还是正确的路径
![image](https://github.com/pengzhanbo/vuepress-theme-plume/assets/151493883/84f4e94a-df58-49b4-a789-f6ee3afb73eb)

点击首页跳转后，就出现了问题
![image](https://github.com/pengzhanbo/vuepress-theme-plume/assets/151493883/98eadc1c-5679-45e6-ae4c-f59b1faf0010)

**Comment by pengzhanbo** [comment]
发现了存在 base 导致的 链接解析生成的错误，这算是一个恶性bug了，我发个版本进行修复。

**Comment by YTAZWC** [comment]
> 发现了存在 base 导致的 链接解析生成的错误，这算是一个恶性bug了，我发个版本进行修复。
> 
> 主题版本升级到 `1.0.0-rc.51` 即可修复该问题。

好的，我刚刚更新了，现在是还不能用pnpm更新到最新这个版本吗

**Comment by pengzhanbo** [comment]
在项目根目录中添加 `.npmrc` 文件，并写入以下内容：

```
strict-peer-dependencies=false
shamefully-hoist=true
shell-emulator=true
```

就可以及时更新了，pnpm 默认的缓存策略，其刷新缓存的机制 偶尔会导致获取不到刚更新的新版本。

**Comment by YTAZWC** [comment]
> 在项目根目录中添加 `.npmrc` 文件，并写入以下内容：
> 
> ```
> strict-peer-dependencies=false
> shamefully-hoist=true
> shell-emulator=true
> ```
> 
> 就可以及时更新了，pnpm 默认的缓存策略，其刷新缓存的机制 偶尔会导致获取不到刚更新的新版本。

还是没办法更新的最新的版本，😢😢

**Comment by pengzhanbo** [comment]
emmm, [npm](https://www.npmjs.com/package/vuepress-theme-plume) 源确实已经更新到 `1.0.0-rc.51`，我在我本地进行 `pnpm add xxx` 也确实安装的是 `1.0.0-rc.51`，而且也已经更新了差不多 1小时了，应该是可以正常拉取到的

**Comment by YTAZWC** [comment]
> emmm, [npm](https://www.npmjs.com/package/vuepress-theme-plume) 源确实已经更新到 `1.0.0-rc.51`，我在我本地进行 `pnpm add xxx` 也确实安装的是 `1.0.0-rc.51`，而且也已经更新了差不多 1小时了，应该是可以正常拉取到的

## 可以了，因为我用的是淘宝的镜像，所以才没有，换成官方镜像就可以了；太感谢作者了😊

## 除此之外还有小问题想请教作者

### 博客页面个人头像展示的问题
就是这样展示不出图片头像
#### 配置文件和图片路径如下：
![image](https://github.com/pengzhanbo/vuepress-theme-plume/assets/151493883/5ccbef53-08ff-4906-b559-71b10d2d284f)

#### 页面效果

![image](https://github.com/pengzhanbo/vuepress-theme-plume/assets/151493883/cc0ad222-b497-4835-b009-340f87c73aae)

### 导航栏的LOGO
#### 但是导航栏的logo可以使用个人头像上相同路径的图片
![image](https://github.com/pengzhanbo/vuepress-theme-plume/assets/151493883/c66dc1df-f3f1-4303-935c-f28db4030039)
#### 展示效果如下
![image](https://github.com/pengzhanbo/vuepress-theme-plume/assets/151493883/55560428-d53f-4671-81b5-6c5789dcafcf)
#### 然后有一个问题就是，没有在主题配置里找到可以配置出和DEMO一样的导航栏logo，就是展示出下面这样的效果

![image](https://github.com/pengzhanbo/vuepress-theme-plume/assets/151493883/0173d754-59fd-4dd2-a5d5-8f80c65834af)

**Comment by pengzhanbo** [comment]
> 博客页面个人头像展示的问题

这个是由于在很早期的时候实现该文能时，忽略了 `base` 选项带来的影响，导致了这个问题，是一个 bug，我会放在下个版本计划中进行修复（大概在本周内修复），目前可以先在配置中把 `base` 拼接上，`/blogs/ok.jpg` 进行使用。

---

> 没有在主题配置里找到可以配置出和DEMO一样的导航栏logo，就是展示出下面这样的效果

我不确定你是单指 logo 还是指 logo + title， 主题的这个效果，是配置了 theme.logo， 和 userConfig.title 实现的:

```diff
 export default defineUserConfig({
   lang: 'zh-CN',
   base: '/',
+  title: 'Plume 主题',
   theme: themePlume({
+    logo: 'logo.png'
   })
 })
```
如果是多语言，可以这样配置：
```diff
 export default defineUserConfig({
   lang: 'zh-CN',
   base: '/',
+  locales: {
+    '/': { title: 'Plume 主题', lang: 'zh-CN' },
+    '/en/': { title: 'Plume Theme', lang: 'en-US' },
+  },
   theme: themePlume({
+    logo: 'logo.png'
   })
 })
```

**Comment by YTAZWC** [comment]
### 可以了，我指的就是logo+title的效果，另外关于base的路径问题，还有归档和标签的路径解析有bug

#### 标签路径bug
![image](https://github.com/pengzhanbo/vuepress-theme-plume/assets/151493883/a9d87ca3-706d-422e-b4d0-0f2f62282e34)

#### 归档路径bug
![image](https://github.com/pengzhanbo/vuepress-theme-plume/assets/151493883/69b9d72f-0e25-4cec-97b9-30a8d46ced97)

### 辛苦作者了，太感谢了😊

**Comment by pengzhanbo** [comment]
我排查下与 `base` 相关的跳转链接，在下个版本中一并修复这些问题。

**Comment by pengzhanbo** [comment]
主题版本 `1.0.0-rc.52` 已可修复 相关问题。

**Comment by YTAZWC** [comment]
> 主题版本 `1.0.0-rc.52` 已可修复 相关问题。

可以了，辛苦作者啦，
![比心](https://github.com/pengzhanbo/vuepress-theme-plume/assets/151493883/23cc9b85-166a-4da5-8ee4-01b73ebed575)
