### ISSUE TITLE
导航栏标题的图标可以用自己的吗？

### ISSUE THREAD

**Issue by Memories7** [pengzhanbo/vuepress-theme-plume#65]
如题，我有一个导航栏标题，用于介绍我自己开发的工具，我想用自己的图标，这种效果能做到吗？

**Comment by pengzhanbo** [comment]
实现这个效果不难，我可以放在下个版本添加该功能。

但由于不确定使用的图标的类型格式，如果是 jpg 等不支持透明度的，可能在切换 浅色/暗色 模式 和 鼠标悬停高亮 时会显得突兀；而即使是支持透明度的如 png，鼠标悬停时可能与文本高亮之间会有一些割裂的效果。所以最好的方式依然是传入 svg 类型的。

现在的 导航栏配置 `icon` 选项是传入的一个 iconify 图标名。
可以将其扩展，支持传入 svg字符串 `{ svg: xxxx }` 或 一个图标链接 `/images/logo.png`。

**Comment by Memories7** [comment]
是的，我明天再试试看，感谢！

**Comment by Memories7** [comment]
好的，谢谢

**Comment by pengzhanbo** [comment]
新版本 `1.0.0-rc.52` 已更新，该功能已添加。

查看 [文档](https://plume.pengzhanbo.cn/config/navigation/#%E9%85%8D%E7%BD%AE) 。
