### ISSUE TITLE
笔记中侧边栏的问题

### ISSUE THREAD

**Issue by YTAZWC** [pengzhanbo/vuepress-theme-plume#70]
### 你好，我按照指南中对笔记的侧边栏进行配置，配置内容如下所示
![image](https://github.com/pengzhanbo/vuepress-theme-plume/assets/151493883/a29b96a7-653c-468e-8fdc-5132b9093da1)

### 但是显示结果确实下面这样的，请问应该怎么配置呢？

![image](https://github.com/pengzhanbo/vuepress-theme-plume/assets/151493883/aaf3bbad-933a-4f11-948d-54b338f19959)

**Comment by pengzhanbo** [comment]
从截图上看，应该是 配置与 目录结构没有对应上。 我不知道你的目录结构是如何的，因此此配置是否正确 无从推定。

但反过来，假设你的配置是正确的，那么你的目录结构应该是：

```sh
  ./{source Dir}
  | notes
     | 卡玛网刷题
        | 46.xxx
        | 54.xxx
        | 55.xxx
```

可以根据这个看看你的目录结构是否正确。 或者请给一个 目录结构树的截图 给我看下

**Comment by YTAZWC** [comment]
我刚刚重新再对照了一下配置，按照主题源码里面，我加了一个dir的配置就可以了：
![image](https://github.com/pengzhanbo/vuepress-theme-plume/assets/151493883/ff1e4923-460a-48ad-8f35-652bca45c9a5)
然后我的目录结构是下面这样的； `README.md`文件是在[卡码网刷题]目录下：
![image](https://github.com/pengzhanbo/vuepress-theme-plume/assets/151493883/1a2c0991-14c3-4409-98b9-a52cfb11a204)
然后的话，结果是可以的：
![image](https://github.com/pengzhanbo/vuepress-theme-plume/assets/151493883/9a223a8a-86d9-489c-b0f5-577c38823279)
但是，这样的话，我要如何显示单个目录呢？比如说下面这样，就是既有折叠的，也有单个一个的：
![image](https://github.com/pengzhanbo/vuepress-theme-plume/assets/151493883/f1012971-5175-43c1-8f9c-60f86a515aa7)

**Comment by pengzhanbo** [comment]
在 `sidebar` 数组中，插入的第一个元素为 `''` 就可以了，主题会自动识别 `''` 为 当前目录下的 `README.md`。

```
sidebar: [
  '',
  { dir: '', items: [] },
]
```

**Comment by YTAZWC** [comment]
好的，感谢，已经可以了🌹
