### ISSUE TITLE
watermark is too simple

### ISSUE THREAD

**Issue by Mister-Hope** [pengzhanbo/vuepress-theme-plume#75]
![image](https://github.com/pengzhanbo/vuepress-theme-plume/assets/33315834/eab75c89-d301-4b16-bf1f-9a8c6e400c31)

The watermark can be easily removed, at least the feature should use a [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) to enforce a watermark once the original one is being removed.

I am suggesting `watermark-js-plus` for this feature, it's not heavy and powerful enough for this, and as mentioned in the other issue, it should be the first option for a plugin like `@vuepress/plugin-watermark`

**Comment by pengzhanbo** [comment]
提交了一个 [PR #111](https://github.com/vuepress/ecosystem/pull/111) , 使用 `watermark-js-plus` 为 VuePress 站点添加水印。 主题后续将会切换到这个新插件。

**Comment by Mister-Hope** [comment]
The pr looks grear, but need a little tweaks.
