### ISSUE TITLE
note 页面有误

### ISSUE THREAD

**Issue by huankong233** [pengzhanbo/vuepress-theme-plume#8]
复现环境： Windows 10
复现过程：

使用的博主的仓库

![image](https://github.com/pengzhanbo/vuepress-theme-plume/assets/49610758/41beb1ee-ab16-4889-addd-d4a65695607a)

左侧 边栏丢失

![image](https://github.com/pengzhanbo/vuepress-theme-plume/assets/49610758/79424455-3575-4bf1-873f-568847377007)

我检查了一下代码，发现是这个变量返回了 `false`

![image](https://github.com/pengzhanbo/vuepress-theme-plume/assets/49610758/8e2f11bf-c071-4335-afd1-d1b755e6738a)

**Comment by pengzhanbo** [comment]
在 windows 下， 由于分隔符的问题，错误的将某些页面匹配为 blog post 类型，导致 sidebar 丢失。
已修复。
