### ISSUE TITLE
优化友情链接页布局

### ISSUE THREAD

**Issue by jiezhuo** [pengzhanbo/vuepress-theme-plume#80]
当前的友情链接页相比于其他页面似乎有些粗糙，能否有机会实现标签分组或单独控制标签背景色的功能呢，类似[这样](https://v2-vuepress-theme-gungnir.vercel.app/links/)。
实际上我打算用来做一个网站导航的功能，但是标签一多就没有层次感，每个标签几乎一样难以区分，不太好使用

**Comment by pengzhanbo** [comment]
可以，我修改下布局，不过由于当前的 `vuepress@2.0.0-rc.11` 存在一些 bug ，我应该会在 `vuepress@2.0.0-rc.12` 发布后再更新本主题。

**Comment by pengzhanbo** [comment]
@jiezhuo 分组功能已支持。

但目前而言，友情链接页 当前的布局与功能 过于简陋，不符合预期。我打算对其进行重构。

**Comment by pengzhanbo** [comment]
@jiezhuo 友情链接页的布局在新的版本中已经进行了重构，与主题保持一致的风格。

**Comment by jiezhuo** [comment]
这次调整非常棒，分级清晰，标签更佳有质感，包含的信息更丰富，字体样式更合理。已经用起来了
