### ISSUE TITLE
blognav 跳转链接异常

### ISSUE THREAD

**Issue by milixiang** [pengzhanbo/vuepress-theme-plume#84]
如下图，两个按钮的href多了个/  导致跳转地址不对 
![image](https://github.com/pengzhanbo/vuepress-theme-plume/assets/12092768/69ac6f61-1f0e-4622-99a5-d005d23f66b9)

**Comment by milixiang** [comment]
照着 https://github.com/pengzhanbo/pengzhanbo.cn 比较了下 发现版本不一致，  我使用的  1.0.0-rc.57 & 2.0.0-rc.12  降到1.0.0-rc.54 & 2.0.0-rc.9后正常了  但是没找到根本原因

**Comment by pengzhanbo** [comment]
> 照着 [pengzhanbo/pengzhanbo.cn](https://github.com/pengzhanbo/pengzhanbo.cn) 比较了下 发现版本不一致， 我使用的 1.0.0-rc.57 & 2.0.0-rc.12 降到1.0.0-rc.54 & 2.0.0-rc.9后正常了 但是没找到根本原因

该问题已在 rc.58 中修复了
