### ISSUE TITLE
Is Custom Styles Overriding Still Available?

### ISSUE THREAD

**Issue by KrLite** [pengzhanbo/vuepress-theme-plume#87]
I wanted to override some default provided css styles (mainly the accent color like `--vp-c-brand-X`), but end up failing after these tries:

1. Using a `index.scss` file at `/docs/.vuepress/styles/index.scss` as mentioned [here (this document contains broken links).](https://plume.pengzhanbo.cn/guide/custom-style/#style-文件)
2. Using a `palette.scss` file at `/docs/.vuepress/styles/palette.scss`.
3. Using a `palette.styl` file at `/docs/.vuepress/styles/palette.styl` as in VuePress 1.
4. Using something similar to a `custom.css` file used in a regular Vue (Vite) app.

I wonder if the ability to introduce custom styles globally still available, and if there's a document I can refer to.

**Comment by pengzhanbo** [comment]
I am sorry for the errors and omissions in this section of the document. I have now updated the document, and you can refer to the [new document](https://theme-plume.vuejs.press/guide/custom-style/) for a custom style.

**Comment by KrLite** [comment]
> I am sorry for the errors and omissions in this section of the document. I have now updated the document, and you can refer to the [new document](https://theme-plume.vuejs.press/guide/custom-style/) for a custom style.

Thanks for the quick response! The new document solves the problem.
