### ISSUE TITLE
请教一下如何在note类型里面配置自定义的永久链接，谢谢！

### ISSUE THREAD

**Issue by mrzhenggang** [pengzhanbo/vuepress-theme-plume#91]
例如永久链接为  /guide/code/group/ 的文章，因为在 notes/theme/guide/代码/代码组.md 路径，并且通过 config.js 中的 notes 进行了匹配，才实现的sidebar 显示。我希望能够实现更加灵活的配置。

例如我放在 /note/usermanual 目录下的文章 /note/usermanual/login.md 和 submit.md 。它们的永久链接分别为 /login 和 /submit，并没有前面的 /usermanual 用来进行 sidebar 匹配，这是该怎么办呢？

感谢！

**Comment by pengzhanbo** [comment]
emmm... 这么做的理由是什么？ 既然在属于同一个 note 下，为什么 永久链接却要这么省略 /usermanual ?

**Comment by mrzhenggang** [comment]
非常感觉您的回复！原因是这样的：

1、我已经有一些文章，不想更改永久链接，比如

https://xxx.com/alamode/

如果我将相同的文章，如软件类别放到您的主题下面，就需要改成 

https://xxx.com/software/alamode/

然后使用 software 作为判断路由的依据

2、因为我想保持灵活性，一篇笔记文章可能现在看来属于 分类A，也许由于调整，就变成了 分类B

谢谢！不知道这样的功能是否很复杂。

无论如何，都感谢您的回复！谢谢！

**Comment by pengzhanbo** [comment]
虽然我建议在同一个笔记写的文章应该拥有相同的路径前缀，同时，也建议如果文章从笔记 A 移动到笔记 B，那么应该是将文章整体都迁移过去，包括文件和链接都应该更新。

我会在下个版本更新一个小功能， 你可以在 文件的 `frontmatter` 中配置 `sidebar` 为指定的 sidebar 路径匹配前缀，会强制在这个页面打开对应的 sidebar。

但我不打算将这个功能写入到文档中，因为这违背了我对 notes 的设计初衷。

```md
---
sidebar: /usermanual/
---
```
