### ISSUE TITLE
 sidebar: 'auto'这样设置后会丢失收缩功能

### ISSUE THREAD

**Issue by meitao20** [pengzhanbo/vuepress-theme-plume#94]
sidebar: 'auto'这样设置后会丢失收缩功能（少一个分组标签），请问要怎样处理
![image](https://github.com/pengzhanbo/vuepress-theme-plume/assets/23448130/3696cfff-5295-4fe7-99f5-b3836ffc04fb)

**Comment by pengzhanbo** [comment]
因为 auto sidebar 功能我还没有对其进行完善，当前只是做了一些比较简单的支持，可以通过 文件名 进行排序，以及根据文件夹结构进行分组，但也忽略了一些配置细节。

目前对 sidebar auto 的完善还没有具体的排期计划，需要等我完成对 主题 的 客户端 代码 小重构后，增强 主题的可扩展性后，才会正式推进其他的功能的改进和完善。 重构的内容比较繁杂，所以进度相对来说比较慢。

**Comment by pengzhanbo** [comment]
auto sidebar 当前版本已进行了重写，分组现在默认展开，并支持收缩。

但就目前而言，auto sidebar 还是缺少更灵活的行为控制的配置方式，目前我没有好思路去完善。欢迎提出建议。
